//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b2004
    {
        public int m1006_cod { get; set; }
        public string b2050_cod { get; set; }
        public string b2001_cod { get; set; }
        public string m1015_cod { get; set; }
        public int b2004_orden { get; set; }
        public string b1001_codtit { get; set; }
        public string b2004_tiptit { get; set; }
        public string b1001_codrep { get; set; }
        public decimal b2004_tpcpar { get; set; }
        public bool b2004_envchq { get; set; }
        public string b2001_perweb { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b2004_datcre { get; set; }
        public string b2004_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b2004_datmod { get; set; }
        public string b2004_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public string b2004_ori { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
    
        public virtual b1001 b1001 { get; set; }
        public virtual b2001 b2001 { get; set; }
    }
}
