//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b3003
    {
        public string b3001_cod { get; set; }
        public string b3001_nom { get; set; }
        public string b3052_cod { get; set; }
        public System.DateTime b3003_dat { get; set; }
        public string b3003_posici { get; set; }
        public decimal b3003_cotiza { get; set; }
        public decimal b3003_maxdia { get; set; }
        public decimal b3003_mindia { get; set; }
        public decimal b3003_apedia { get; set; }
        public decimal b3003_nomdia { get; set; }
        public decimal b3003_efedia { get; set; }
        public decimal b3003_bid { get; set; }
        public decimal b3003_ask { get; set; }
        public decimal b3003_voltit { get; set; }
        public decimal b3003_delta { get; set; }
        public decimal b3003_volati { get; set; }
        public decimal b3003_posabi { get; set; }
        public decimal b3003_cupcor { get; set; }
        public decimal b3003_tirmer { get; set; }
        public string b3003_notas { get; set; }
        public string b3003_tipcar { get; set; }
        public decimal b3003_difere { get; set; }
        public decimal b3003_variac { get; set; }
        public decimal b3003_maxanu { get; set; }
        public Nullable<System.DateTime> b3003_datmax { get; set; }
        public decimal b3003_minanu { get; set; }
        public Nullable<System.DateTime> b3003_datmin { get; set; }
        public int b3003_frecue { get; set; }
        public decimal b3003_duraci { get; set; }
        public decimal b3003_convex { get; set; }
        public Nullable<int> b3050_cod { get; set; }
        public string b3056_cod { get; set; }
        public string b3003_origen { get; set; }
        public decimal b3003_cothis { get; set; }
        public decimal b3003_cotant { get; set; }
        public byte b3003_real { get; set; }
        public decimal b3003_ciegae { get; set; }
        public decimal b3003_tircie { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b3003_datcre { get; set; }
        public string b3003_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b3003_datmod { get; set; }
        public string b3003_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public int b3095_num { get; set; }
        public decimal b3003_numpar { get; set; }
        public decimal b3003_patrim { get; set; }
        public decimal b3003_bet6md { get; set; }
        public decimal b3003_bet2as { get; set; }
        public decimal b3003_divyie { get; set; }
    
        public virtual b3002 b3002 { get; set; }
    }
}
