//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b3002
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public b3002()
        {
            this.b3003 = new HashSet<b3003>();
            this.b5004 = new HashSet<b5004>();
        }
    
        public string b3001_cod { get; set; }
        public string b3052_cod { get; set; }
        public string b3002_codmer { get; set; }
        public string m1015_cod { get; set; }
        public string b3002_cotneg { get; set; }
        public string b3002_notas { get; set; }
        public string b3002_codblo { get; set; }
        public decimal b3002_faccot { get; set; }
        public string b3002_motnco { get; set; }
        public bool b3002_moneda { get; set; }
        public string b3002_carct1 { get; set; }
        public string b3002_carct2 { get; set; }
        public string b3002_codib1 { get; set; }
        public string b3002_codib2 { get; set; }
        public bool b3002_var { get; set; }
        public int b3002_subcta { get; set; }
        public string b3002_codvch { get; set; }
        public string b3001_cotiza { get; set; }
        public string b5013_mer { get; set; }
        public string b3002_submer { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b3002_datcre { get; set; }
        public string b3002_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b3002_datmod { get; set; }
        public string b3002_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public byte b3002_repres { get; set; }
        public decimal b3002_canlot { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public bool b3002_cupcor { get; set; }
    
        public virtual b3001 b3001 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b3003> b3003 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b5004> b5004 { get; set; }
    }
}
