//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b3040
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public b3040()
        {
            this.b5001 = new HashSet<b5001>();
            this.b5004 = new HashSet<b5004>();
        }
    
        public int b3040_num { get; set; }
        public string b3001_cod { get; set; }
        public string b3040_tipavi { get; set; }
        public Nullable<System.DateTime> b3040_datpre { get; set; }
        public string m1008_codres { get; set; }
        public string b3040_fuente { get; set; }
        public string b3040_aviso { get; set; }
        public string b3040_tipmer { get; set; }
        public string b3040_numeve { get; set; }
        public string b3040_txt__1 { get; set; }
        public string b3040_txt__2 { get; set; }
        public string b3040_txt__3 { get; set; }
        public string b3040_txt__4 { get; set; }
        public string b3040_txt__5 { get; set; }
        public string b3040_txt__6 { get; set; }
        public string b3040_txt__7 { get; set; }
        public string b3040_txt__8 { get; set; }
        public string b3040_txt__9 { get; set; }
        public string b3040_txt__10 { get; set; }
        public string b3040_obs { get; set; }
        public Nullable<System.DateTime> b3040_datcor { get; set; }
        public Nullable<System.DateTime> b3040_datliq { get; set; }
        public string m1015_cod { get; set; }
        public decimal b3040_impori { get; set; }
        public decimal b3040_impbru { get; set; }
        public decimal b3040_impnet { get; set; }
        public decimal b3040_retori { get; set; }
        public decimal b3040_ret { get; set; }
        public byte b3040_declar { get; set; }
        public string b3001_codnou { get; set; }
        public decimal b3040_nuevas { get; set; }
        public decimal b3040_viejas { get; set; }
        public decimal b3040_precio { get; set; }
        public decimal b3040_nomina { get; set; }
        public string m1036_cod { get; set; }
        public Nullable<System.DateTime> b3040_datres { get; set; }
        public Nullable<System.DateTime> b3040_datimp { get; set; }
        public string b3040_texto { get; set; }
        public System.DateTime b3040_datano { get; set; }
        public Nullable<System.DateTime> b3040_datinf { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b3040_datcre { get; set; }
        public string b3040_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b3040_datmod { get; set; }
        public string b3040_hormod { get; set; }
        public Nullable<System.DateTime> b3040_exdate { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public decimal b3040_patmin { get; set; }
        public decimal b3040_tpcliq { get; set; }
        public string b3040_tippet { get; set; }
        public string b2054_cod { get; set; }
        public decimal b3040_tpcpat { get; set; }
        public decimal b3040_impmin { get; set; }
        public string b3040_reside { get; set; }
        public decimal b3040_impmax { get; set; }
        public string b2054_cod1 { get; set; }
        public int b3040_numvot { get; set; }
        public string b3052_cod { get; set; }
        public bool b3040_prefer { get; set; }
        public string b3041_liscod { get; set; }
        public Nullable<int> m9915_num { get; set; }
        public bool b3040_routin { get; set; }
        public string b3040_fracci { get; set; }
        public string b3040_signo { get; set; }
        public Nullable<System.DateTime> b3040_datpar { get; set; }
        public string b3040_codbic { get; set; }
        public string b3040_disder { get; set; }
        public string b3040_refmsj { get; set; }
        public string b3040_obl { get; set; }
        public Nullable<System.DateTime> b3040_datage { get; set; }
        public Nullable<System.DateTime> b3040_datefe { get; set; }
        public Nullable<System.DateTime> b3040_datexp { get; set; }
        public Nullable<System.DateTime> b3040_datsus { get; set; }
        public string b3040_numvin { get; set; }
    
        public virtual b3001 b3001 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b5001> b5001 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b5004> b5004 { get; set; }
    }
}
