//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b3050
    {
        public int b3050_cod { get; set; }
        public string b3050_nom { get; set; }
        public string m1009_cod { get; set; }
        public string b3050_nif { get; set; }
        public string b3050_pagweb { get; set; }
        public string b3058_cod { get; set; }
        public string b3050_claent { get; set; }
        public Nullable<byte> b3050_act { get; set; }
        public string b3050_nomred { get; set; }
        public string b3050_tipo { get; set; }
        public string b3062_cod { get; set; }
        public bool b3050_llevan { get; set; }
        public decimal b3050_capsoc { get; set; }
        public Nullable<System.DateTime> b3050_datbaj { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b3050_datcre { get; set; }
        public string b3050_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b3050_datmod { get; set; }
        public string b3050_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public string b3051_cod { get; set; }
        public Nullable<decimal> b3050_intdiv { get; set; }
        public Nullable<decimal> b3050_decdiv { get; set; }
        public Nullable<System.DateTime> b3050_datins { get; set; }
        public string b3050_datreg { get; set; }
        public bool b3050_adm { get; set; }
        public string b2054_cod { get; set; }
        public string b3050_consti { get; set; }
        public string b3050_tipiic { get; set; }
        public Nullable<System.DateTime> b3050_datcon { get; set; }
        public bool b3050_iic { get; set; }
        public string b3050_admin { get; set; }
        public string b3068_cod { get; set; }
        public string b3050_audita { get; set; }
        public string b3037_result { get; set; }
        public bool b4051_compar { get; set; }
        public string b4051_nrcnmv { get; set; }
        public bool b4051_clases { get; set; }
        public Nullable<int> m1006_cod { get; set; }
        public string b3050_dom { get; set; }
        public Nullable<decimal> b3050_tpcinv { get; set; }
        public string m1027_cod { get; set; }
        public Nullable<int> m1006_codpro { get; set; }
        public string b3050_domnum { get; set; }
        public string b2001_codpro { get; set; }
        public string b2050_codpro { get; set; }
        public string b3050_cpo { get; set; }
        public string m1058_sigla { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public string b2054_coddep { get; set; }
        public string b3050_idcod { get; set; }
        public bool b3050_pasapo { get; set; }
        public string b2054_codliq { get; set; }
        public string b3050_notas { get; set; }
        public string b3050_adiliq { get; set; }
        public string b3050_adicom { get; set; }
        public string b3022_moodys { get; set; }
        public string b3022_sp { get; set; }
        public string b3022_fitibc { get; set; }
        public string b4070_tipfon { get; set; }
        public string b3050_discom { get; set; }
        public string b3050_ambito { get; set; }
        public string b3050_nomcom { get; set; }
        public string b3050_roac { get; set; }
        public bool b3050_iicext { get; set; }
        public string b3050_domcom { get; set; }
        public string b3050_bic { get; set; }
        public string b3050_delega { get; set; }
    }
}
