//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b5042
    {
        public int b3050_cod { get; set; }
        public string b3001_cod { get; set; }
        public int b5042_num { get; set; }
        public int b5040_num { get; set; }
        public int b5042_numini { get; set; }
        public int b5042_numfin { get; set; }
        public string b5042_tipope { get; set; }
        public System.DateTime b5042_datalt { get; set; }
        public string b5042_tipopb { get; set; }
        public Nullable<System.DateTime> b5042_datbaj { get; set; }
        public string m1036_cod { get; set; }
        public string b5042_notape { get; set; }
        public string b5042_notcie { get; set; }
        public int b5042_numant { get; set; }
        public string b2054_cod { get; set; }
        public decimal b5042_camape { get; set; }
        public decimal b5042_camcie { get; set; }
        public string m1008_codcre { get; set; }
        public System.DateTime b5042_datcre { get; set; }
        public string b5042_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public System.DateTime b5042_datmod { get; set; }
        public string b5042_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public Nullable<System.DateTime> b5042_datcon { get; set; }
        public decimal b5042_nomina { get; set; }
        public string b5042_refreg { get; set; }
        public string b5042_sclv { get; set; }
        public string b5042_codbol { get; set; }
        public decimal b5042_canblo { get; set; }
        public decimal b5042_cantid { get; set; }
    
        public virtual b5040 b5040 { get; set; }
    }
}
