//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b5041
    {
        public int b3050_cod { get; set; }
        public int b5040_num { get; set; }
        public int b5041_num { get; set; }
        public string b2004_tiptit { get; set; }
        public string b1001_codtit { get; set; }
        public string b1001_codrep { get; set; }
        public string b1001_codrep2 { get; set; }
        public string b1001_codrep3 { get; set; }
        public decimal b5041_tpcpar { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b5041_datcre { get; set; }
        public string b5041_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b5041_datmod { get; set; }
        public string b5041_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public string b5041_cpo { get; set; }
        public string b5041_pob { get; set; }
        public string b5041_dom { get; set; }
        public string m1009_codnac { get; set; }
        public string m1009_cod { get; set; }
        public byte b5041_titbia { get; set; }
        public string b5041_nom { get; set; }
        public string b5041_nif { get; set; }
    }
}
