//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b5052
    {
        public string b5052_cod { get; set; }
        public string b5052_nom { get; set; }
        public string b5052_nomred { get; set; }
        public byte b5052_usoint { get; set; }
        public string b5052_nomext { get; set; }
        public string b5001_clamov { get; set; }
        public byte b5052_emicom { get; set; }
        public byte b5052_comope { get; set; }
        public byte b5052_efecto { get; set; }
        public byte b5052_domici { get; set; }
        public int b5052_diasva { get; set; }
        public string b5052_horlim { get; set; }
        public string b5052_texcom { get; set; }
        public byte b5052_car { get; set; }
        public string b5052_tmdgte { get; set; }
        public string b5052_forimp { get; set; }
        public byte b5052_balpag { get; set; }
        public byte b5052_movefe { get; set; }
        public byte b5052_remesa { get; set; }
        public string b5052_codbe { get; set; }
        public bool b5052_invdes { get; set; }
        public byte b5052_coresp { get; set; }
        public byte b5052_ingadm { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b5052_datcre { get; set; }
        public string b5052_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b5052_datmod { get; set; }
        public string b5052_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public string b5052_sep { get; set; }
        public byte b5052_hisfis { get; set; }
        public string b5052_codext { get; set; }
        public byte b5052_activo { get; set; }
        public string m1011_cod { get; set; }
        public string b5052_obs { get; set; }
        public string b5052_tipcon { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public string m1012_cod { get; set; }
        public string b5052_sigefe { get; set; }
        public string b5052_sigtit { get; set; }
        public bool b5052_entman { get; set; }
        public bool b5052_afepar { get; set; }
        public string b5052_codgas { get; set; }
        public bool b5052_renefe { get; set; }
    }
}
