//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesgloseGastos_Cuentas
    {
        public int Id { get; set; }
        public string FnAmpliacionReduccionesAutocartera { get; set; }
        public string FnComisionFija { get; set; }
        public string FnComisionVariable { get; set; }
        public string FnComisionDepositario { get; set; }
        public string FnGastosTasaRegistrosOficiales { get; set; }
        public string FnGastosAdmisionCotizacionBolsa { get; set; }
        public string FnGastosDiferenciaPeriodificaciones { get; set; }
        public string FnGastosBancarios { get; set; }
        public string FnGastosRegistroLibroAccionistas { get; set; }
        public string FnAuditoriaCuentas { get; set; }
        public string FnOtros { get; set; }
        public string FnImpuestoSobreSociedades { get; set; }
    }
}
