//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrumentos_Importados
    {
        public string ISIN { get; set; }
        public string IdTipoInstrumento { get; set; }
        public string IdTipoInstrumento2 { get; set; }
        public string IdTipoInstrumento3 { get; set; }
        public Nullable<int> IdSector { get; set; }
        public Nullable<bool> Emergente { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string IdInstrumento { get; set; }
        public Nullable<int> IdZona { get; set; }
        public Nullable<int> IdPais { get; set; }
        public string TickerBloomberg { get; set; }
        public Nullable<decimal> PuntuacionSmallBig { get; set; }
        public Nullable<decimal> PuntaucionValueGrowth { get; set; }
        public Nullable<decimal> PuntuacionUta { get; set; }
        public string CoreTrading { get; set; }
    
        public virtual Instrumento Instrumento { get; set; }
        public virtual Instrumentos_Categorias Instrumentos_Categorias { get; set; }
        public virtual Instrumentos_Empresas Instrumentos_Empresas { get; set; }
        public virtual Instrumentos_Paises Instrumentos_Paises { get; set; }
        public virtual Instrumentos_Sectores Instrumentos_Sectores { get; set; }
        public virtual Instrumentos_Tipos Instrumentos_Tipos { get; set; }
        public virtual Instrumentos_Tipos Instrumentos_Tipos1 { get; set; }
        public virtual Instrumentos_Tipos Instrumentos_Tipos2 { get; set; }
        public virtual Instrumentos_Zonas Instrumentos_Zonas { get; set; }
    }
}
