//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_IndicePreconfiguradoNovarex
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string Descripcion { get; set; }
        public int IdTipoFormula { get; set; }
        public string IdInstrumento { get; set; }
        public Nullable<int> IdInstrumentoZona { get; set; }
        public string Divisa { get; set; }
        public string Formula { get; set; }
        public string IndiceReferencia { get; set; }
        public Nullable<int> IdIndicesPreconfiguradosNovarex { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
