//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_PlusvaliasDividendos_ISINS
    {
        public int Id { get; set; }
        public int Id_Parametros_PlusvaliasDividendos { get; set; }
        public string ISIN { get; set; }
    
        public virtual Parametros_PlusvaliasDividendos Parametros_PlusvaliasDividendos { get; set; }
    }
}
