//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipesSalat_Aportaciones
    {
        public int Id { get; set; }
        public int IdParticipeSalat { get; set; }
        public decimal Aportacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdTitular { get; set; }
        public string Titular { get; set; }
    
        public virtual ParticipesSalat ParticipesSalat { get; set; }
    }
}
