//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantillas_Indices_Referencia
    {
        public int Id { get; set; }
        public Nullable<int> IdTipoIndiceReferencia { get; set; }
        public string Codigo { get; set; }
        public string DescripcionCodigo { get; set; }
        public string CodigoIc { get; set; }
    
        public virtual Indices_Referencia_Tipos Indices_Referencia_Tipos { get; set; }
        public virtual Plantilla Plantilla { get; set; }
    }
}
