//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plantilla()
        {
            this.Parametros_CarteraRF = new HashSet<Parametros_CarteraRF>();
            this.Parametros_CompraVentaPrecAdq = new HashSet<Parametros_CompraVentaPrecAdq>();
            this.Parametros_DistribucionPatrimonioNovarex = new HashSet<Parametros_DistribucionPatrimonioNovarex>();
            this.Parametros_DistribucionPatrimonioNovarex_Tipos = new HashSet<Parametros_DistribucionPatrimonioNovarex_Tipos>();
            this.Parametros_DividendosCobrados = new HashSet<Parametros_DividendosCobrados>();
            this.Parametros_EvolucionMercados = new HashSet<Parametros_EvolucionMercados>();
            this.Parametros_EvolucionPatrimGuissona = new HashSet<Parametros_EvolucionPatrimGuissona>();
            this.Parametros_EvolucionPatrimonioConjuntoGuissona = new HashSet<Parametros_EvolucionPatrimonioConjuntoGuissona>();
            this.Parametros_EvolucionPatrimonioConjuntoGuissona_Fondos = new HashSet<Parametros_EvolucionPatrimonioConjuntoGuissona_Fondos>();
            this.Parametros_EvolucionRentabilidadGuissona = new HashSet<Parametros_EvolucionRentabilidadGuissona>();
            this.Parametros_EvolucionRentabilidadGuissona_Fondos = new HashSet<Parametros_EvolucionRentabilidadGuissona_Fondos>();
            this.Parametros_GraficoBenchmark = new HashSet<Parametros_GraficoBenchmark>();
            this.Parametros_GraficoBenchmark_Indices = new HashSet<Parametros_GraficoBenchmark_Indices>();
            this.Parametros_GraficoCompPatrimonioTipoProducto = new HashSet<Parametros_GraficoCompPatrimonioTipoProducto>();
            this.Parametros_IIC_ComprasVentasEjercicio = new HashSet<Parametros_IIC_ComprasVentasEjercicio>();
            this.Parametros_IndicePreconfiguradoNovarex = new HashSet<Parametros_IndicePreconfiguradoNovarex>();
            this.Parametros_IndicePreconfiguradoNovarex_Otros = new HashSet<Parametros_IndicePreconfiguradoNovarex_Otros>();
            this.Parametros_OperacionesRentaVariable_II = new HashSet<Parametros_OperacionesRentaVariable_II>();
            this.Parametros_PlusvaliasDividendos = new HashSet<Parametros_PlusvaliasDividendos>();
            this.Parametros_RatiosCarteraRV = new HashSet<Parametros_RatiosCarteraRV>();
            this.Parametros_Rentabilidad_CarteraII = new HashSet<Parametros_Rentabilidad_CarteraII>();
            this.Parametros_RFComprasVentasEjercicio = new HashSet<Parametros_RFComprasVentasEjercicio>();
            this.Parametros_RVComprasRealizadasEjercicio = new HashSet<Parametros_RVComprasRealizadasEjercicio>();
            this.Parametros_VariacionPatrimonialB = new HashSet<Parametros_VariacionPatrimonialB>();
            this.Plantillas_Estrategias = new HashSet<Plantillas_Estrategias>();
            this.Plantillas_Generaciones_Isins = new HashSet<Plantillas_Generaciones_Isins>();
            this.Plantillas_Generaciones_Participes = new HashSet<Plantillas_Generaciones_Participes>();
            this.Plantillas_Generaciones_Plantilla = new HashSet<Plantillas_Generaciones_Plantilla>();
            this.Plantillas_Generaciones_Secciones = new HashSet<Plantillas_Generaciones_Secciones>();
            this.Plantillas_Indices_Referencia = new HashSet<Plantillas_Indices_Referencia>();
            this.Plantillas_Isins_Hist = new HashSet<Plantillas_Isins_Hist>();
            this.Plantillas_Isins = new HashSet<Plantillas_Isins>();
            this.Plantillas_Participes = new HashSet<Plantillas_Participes>();
            this.Plantillas_Secciones_Hist = new HashSet<Plantillas_Secciones_Hist>();
            this.Plantillas_Secciones = new HashSet<Plantillas_Secciones>();
            this.Preview_CompraVentaPrecAdq = new HashSet<Preview_CompraVentaPrecAdq>();
            this.Preview_RentaFija = new HashSet<Preview_RentaFija>();
            this.Preview_RentaVariable = new HashSet<Preview_RentaVariable>();
            this.PRO_02_Table = new HashSet<PRO_02_Table>();
            this.PRO_025_Table = new HashSet<PRO_025_Table>();
            this.PRO_03_Table = new HashSet<PRO_03_Table>();
            this.PRO_10_Table = new HashSet<PRO_10_Table>();
            this.PRO_13_Table = new HashSet<PRO_13_Table>();
            this.PRO_17_Table = new HashSet<PRO_17_Table>();
            this.RentabilidadCarteraSolemegs = new HashSet<RentabilidadCarteraSolemeg>();
            this.Temp_Burbujas = new HashSet<Temp_Burbujas>();
            this.Temp_CarteraCcrVolgaGamar = new HashSet<Temp_CarteraCcrVolgaGamar>();
            this.Temp_CarteraRF = new HashSet<Temp_CarteraRF>();
            this.Temp_CompraVentaPrecAdq = new HashSet<Temp_CompraVentaPrecAdq>();
            this.Temp_DistribucionPatrimonioNovarex_Cartera = new HashSet<Temp_DistribucionPatrimonioNovarex_Cartera>();
            this.Temp_DistribucionPatrimonioNovarex_Tesoreria = new HashSet<Temp_DistribucionPatrimonioNovarex_Tesoreria>();
            this.Temp_DividendosCobrados = new HashSet<Temp_DividendosCobrados>();
            this.Temp_EvolucionIndBench = new HashSet<Temp_EvolucionIndBench>();
            this.Temp_EvolucionMercados = new HashSet<Temp_EvolucionMercados>();
            this.Temp_EvolucionPatrGuissonaIndBench = new HashSet<Temp_EvolucionPatrGuissonaIndBench>();
            this.Temp_EvolucionPatrGuissonaRentabilidad = new HashSet<Temp_EvolucionPatrGuissonaRentabilidad>();
            this.Temp_EvolucionPatrGuissonaValLiq = new HashSet<Temp_EvolucionPatrGuissonaValLiq>();
            this.Temp_EvolucionRentabilidadGuissona = new HashSet<Temp_EvolucionRentabilidadGuissona>();
            this.Temp_EvolucionRentabilidadGuissona_TAE = new HashSet<Temp_EvolucionRentabilidadGuissona_TAE>();
            this.Temp_GraficoExposMercDivisas = new HashSet<Temp_GraficoExposMercDivisas>();
            this.Temp_GraficoCompCarteraRF = new HashSet<Temp_GraficoCompCarteraRF>();
            this.Temp_GraficoCompCarteraRV = new HashSet<Temp_GraficoCompCarteraRV>();
            this.Temp_GraficoExposMercTipoActivo = new HashSet<Temp_GraficoExposMercTipoActivo>();
            this.Temp_GraficoCompPatrimonioDivisas = new HashSet<Temp_GraficoCompPatrimonioDivisas>();
            this.Temp_GraficoCompPatrimonioTipoActivo = new HashSet<Temp_GraficoCompPatrimonioTipoActivo>();
            this.Temp_GraficoCompPatrimonioTipoProducto = new HashSet<Temp_GraficoCompPatrimonioTipoProducto>();
            this.Temp_GraficoExposMercTipoProducto = new HashSet<Temp_GraficoExposMercTipoProducto>();
            this.Temp_IIC_ComprasVentasEjercicio = new HashSet<Temp_IIC_ComprasVentasEjercicio>();
            this.Temp_IndicePreconfiguradoNovarex = new HashSet<Temp_IndicePreconfiguradoNovarex>();
            this.Temp_ListadoRentaFijaNovarex = new HashSet<Temp_ListadoRentaFijaNovarex>();
            this.Temp_OperacionesRentaVariable_II = new HashSet<Temp_OperacionesRentaVariable_II>();
            this.Temp_Participes_Hist = new HashSet<Temp_Participes_Hist>();
            this.Temp_Participes = new HashSet<Temp_Participes>();
            this.Temp_PlusvaliasDividendos = new HashSet<Temp_PlusvaliasDividendos>();
            this.Temp_EvolucionPatrValLiq = new HashSet<Temp_EvolucionPatrValLiq>();
            this.Temp_RatiosCarteraRV = new HashSet<Temp_RatiosCarteraRV>();
            this.Temp_RentabilidadCarteraSolemeg = new HashSet<Temp_RentabilidadCarteraSolemeg>();
            this.Temp_RentaFija = new HashSet<Temp_RentaFija>();
            this.Temp_SuscripcionesReembolsos = new HashSet<Temp_SuscripcionesReembolsos>();
            this.Temp_VariacionPatrimonialB = new HashSet<Temp_VariacionPatrimonialB>();
            this.Temp_VariacionPatrimonialA = new HashSet<Temp_VariacionPatrimonialA>();
            this.Temp_VariacionPatrimonialA_Totales = new HashSet<Temp_VariacionPatrimonialA_Totales>();
            this.Temp_DesgloseGastos = new HashSet<Temp_DesgloseGastos>();
        }
    
        public string CodigoIc { get; set; }
        public int IdTipo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<decimal> ReferenciaTAE { get; set; }
        public int PerfilRiesgo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_CarteraRF> Parametros_CarteraRF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_CompraVentaPrecAdq> Parametros_CompraVentaPrecAdq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_DistribucionPatrimonioNovarex> Parametros_DistribucionPatrimonioNovarex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_DistribucionPatrimonioNovarex_Tipos> Parametros_DistribucionPatrimonioNovarex_Tipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_DividendosCobrados> Parametros_DividendosCobrados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_EvolucionMercados> Parametros_EvolucionMercados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_EvolucionPatrimGuissona> Parametros_EvolucionPatrimGuissona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_EvolucionPatrimonioConjuntoGuissona> Parametros_EvolucionPatrimonioConjuntoGuissona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_EvolucionPatrimonioConjuntoGuissona_Fondos> Parametros_EvolucionPatrimonioConjuntoGuissona_Fondos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_EvolucionRentabilidadGuissona> Parametros_EvolucionRentabilidadGuissona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_EvolucionRentabilidadGuissona_Fondos> Parametros_EvolucionRentabilidadGuissona_Fondos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_GraficoBenchmark> Parametros_GraficoBenchmark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_GraficoBenchmark_Indices> Parametros_GraficoBenchmark_Indices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_GraficoCompPatrimonioTipoProducto> Parametros_GraficoCompPatrimonioTipoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_IIC_ComprasVentasEjercicio> Parametros_IIC_ComprasVentasEjercicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_IndicePreconfiguradoNovarex> Parametros_IndicePreconfiguradoNovarex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_IndicePreconfiguradoNovarex_Otros> Parametros_IndicePreconfiguradoNovarex_Otros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_OperacionesRentaVariable_II> Parametros_OperacionesRentaVariable_II { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_PlusvaliasDividendos> Parametros_PlusvaliasDividendos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_RatiosCarteraRV> Parametros_RatiosCarteraRV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_Rentabilidad_CarteraII> Parametros_Rentabilidad_CarteraII { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_RFComprasVentasEjercicio> Parametros_RFComprasVentasEjercicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_RVComprasRealizadasEjercicio> Parametros_RVComprasRealizadasEjercicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_VariacionPatrimonialB> Parametros_VariacionPatrimonialB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Estrategias> Plantillas_Estrategias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Generaciones_Isins> Plantillas_Generaciones_Isins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Generaciones_Participes> Plantillas_Generaciones_Participes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Generaciones_Plantilla> Plantillas_Generaciones_Plantilla { get; set; }
        public virtual Plantillas_Generaciones Plantillas_Generaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Generaciones_Secciones> Plantillas_Generaciones_Secciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Indices_Referencia> Plantillas_Indices_Referencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Isins_Hist> Plantillas_Isins_Hist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Isins> Plantillas_Isins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Participes> Plantillas_Participes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Secciones_Hist> Plantillas_Secciones_Hist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Secciones> Plantillas_Secciones { get; set; }
        public virtual Tipos Tipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preview_CompraVentaPrecAdq> Preview_CompraVentaPrecAdq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preview_RentaFija> Preview_RentaFija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preview_RentaVariable> Preview_RentaVariable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRO_02_Table> PRO_02_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRO_025_Table> PRO_025_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRO_03_Table> PRO_03_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRO_10_Table> PRO_10_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRO_13_Table> PRO_13_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRO_17_Table> PRO_17_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentabilidadCarteraSolemeg> RentabilidadCarteraSolemegs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Burbujas> Temp_Burbujas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_CarteraCcrVolgaGamar> Temp_CarteraCcrVolgaGamar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_CarteraRF> Temp_CarteraRF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_CompraVentaPrecAdq> Temp_CompraVentaPrecAdq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_DistribucionPatrimonioNovarex_Cartera> Temp_DistribucionPatrimonioNovarex_Cartera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_DistribucionPatrimonioNovarex_Tesoreria> Temp_DistribucionPatrimonioNovarex_Tesoreria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_DividendosCobrados> Temp_DividendosCobrados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_EvolucionIndBench> Temp_EvolucionIndBench { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_EvolucionMercados> Temp_EvolucionMercados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_EvolucionPatrGuissonaIndBench> Temp_EvolucionPatrGuissonaIndBench { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_EvolucionPatrGuissonaRentabilidad> Temp_EvolucionPatrGuissonaRentabilidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_EvolucionPatrGuissonaValLiq> Temp_EvolucionPatrGuissonaValLiq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_EvolucionRentabilidadGuissona> Temp_EvolucionRentabilidadGuissona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_EvolucionRentabilidadGuissona_TAE> Temp_EvolucionRentabilidadGuissona_TAE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_GraficoExposMercDivisas> Temp_GraficoExposMercDivisas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_GraficoCompCarteraRF> Temp_GraficoCompCarteraRF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_GraficoCompCarteraRV> Temp_GraficoCompCarteraRV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_GraficoExposMercTipoActivo> Temp_GraficoExposMercTipoActivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_GraficoCompPatrimonioDivisas> Temp_GraficoCompPatrimonioDivisas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_GraficoCompPatrimonioTipoActivo> Temp_GraficoCompPatrimonioTipoActivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_GraficoCompPatrimonioTipoProducto> Temp_GraficoCompPatrimonioTipoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_GraficoExposMercTipoProducto> Temp_GraficoExposMercTipoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_IIC_ComprasVentasEjercicio> Temp_IIC_ComprasVentasEjercicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_IndicePreconfiguradoNovarex> Temp_IndicePreconfiguradoNovarex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_ListadoRentaFijaNovarex> Temp_ListadoRentaFijaNovarex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_OperacionesRentaVariable_II> Temp_OperacionesRentaVariable_II { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Participes_Hist> Temp_Participes_Hist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Participes> Temp_Participes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_PlusvaliasDividendos> Temp_PlusvaliasDividendos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_EvolucionPatrValLiq> Temp_EvolucionPatrValLiq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_RatiosCarteraRV> Temp_RatiosCarteraRV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_RentabilidadCarteraSolemeg> Temp_RentabilidadCarteraSolemeg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_RentaFija> Temp_RentaFija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_SuscripcionesReembolsos> Temp_SuscripcionesReembolsos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_VariacionPatrimonialB> Temp_VariacionPatrimonialB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_VariacionPatrimonialA> Temp_VariacionPatrimonialA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_VariacionPatrimonialA_Totales> Temp_VariacionPatrimonialA_Totales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_DesgloseGastos> Temp_DesgloseGastos { get; set; }
    }
}
