//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preview_CompraVentaPrecAdq
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string Isin { get; set; }
        public string IsinNew { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaNew { get; set; }
        public string Tipo { get; set; }
        public string TipoNew { get; set; }
        public Nullable<decimal> Titulos { get; set; }
        public Nullable<decimal> TitulosNew { get; set; }
        public string DescripcionValor { get; set; }
        public string DescripcionValorNew { get; set; }
        public Nullable<decimal> Adquisicion { get; set; }
        public Nullable<decimal> AdquisicionNew { get; set; }
        public System.DateTime FechaInforme { get; set; }
        public bool IsVisible { get; set; }
        public bool Added { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
