//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_11_Table
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string Tipo { get; set; }
        public string DescripcionValor { get; set; }
        public string Divisa { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public Nullable<decimal> Nominal { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> EfectivoCompra { get; set; }
        public Nullable<decimal> TIR_C_Fif { get; set; }
        public Nullable<decimal> CosteMedio { get; set; }
        public Nullable<decimal> ValorActualDivisa { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public Nullable<decimal> Intereses { get; set; }
        public Nullable<decimal> Plusvalias { get; set; }
        public Nullable<decimal> Minusvalias { get; set; }
        public Nullable<decimal> EfectivoActual { get; set; }
        public Nullable<decimal> PorcentajeP { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
    }
}
