//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingsEquivalencia
    {
        public string Rating { get; set; }
        public string SP { get; set; }
        public string Moody { get; set; }
        public string Fitch { get; set; }
        public Nullable<int> Orden { get; set; }
    }
}
