//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seccione()
        {
            this.Hist_Plantillas_Secciones = new HashSet<Hist_Plantillas_Secciones>();
            this.Plantillas_Generaciones_Secciones = new HashSet<Plantillas_Generaciones_Secciones>();
            this.Plantillas_Secciones = new HashSet<Plantillas_Secciones>();
            this.Plantillas_Secciones_Hist = new HashSet<Plantillas_Secciones_Hist>();
            this.SeccionesProcedimientos = new HashSet<SeccionesProcedimiento>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public bool TienePreview { get; set; }
        public bool TieneValidacionesPrevias { get; set; }
        public bool TieneParametrosPrevios { get; set; }
        public bool Clases { get; set; }
        public bool TieneAlertas { get; set; }
        public bool DependienteRV { get; set; }
        public bool DependienteRF { get; set; }
        public bool Landscape { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hist_Plantillas_Secciones> Hist_Plantillas_Secciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Generaciones_Secciones> Plantillas_Generaciones_Secciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Secciones> Plantillas_Secciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Secciones_Hist> Plantillas_Secciones_Hist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeccionesProcedimiento> SeccionesProcedimientos { get; set; }
    }
}
