//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class session_state
    {
        public string session_id { get; set; }
        public string resource_id { get; set; }
        public System.DateTime modified_date { get; set; }
        public byte[] resource_data { get; set; }
    }
}
