//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Burbujas
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string Isin { get; set; }
        public string DescripcionInstrumento { get; set; }
        public Nullable<decimal> CapitalizacionBursatilEuros { get; set; }
        public Nullable<decimal> PorcentajeCartera { get; set; }
        public Nullable<decimal> DescuentoFundamental { get; set; }
        public System.DateTime FechaCotizacion { get; set; }
        public string TickerBloomberg { get; set; }
        public Nullable<decimal> PuntuacionSmallBig { get; set; }
        public Nullable<decimal> PuntuacionValueGrowth { get; set; }
        public Nullable<decimal> PuntuacionUta { get; set; }
        public bool Visible { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
