//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_EvolucionPatrGuissonaRentabilidad
    {
        public int Id { get; set; }
        public string CodigoIc { get; set; }
        public decimal RentabilidadNeta { get; set; }
        public decimal TasaGestion { get; set; }
        public decimal ComisionDepositaria { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
