//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class a1006
    {
        public int ejerci { get; set; }
        public int m1006_cod { get; set; }
        public int a1005_cod { get; set; }
        public Nullable<int> a1006_nsec { get; set; }
        public string a1001_cod { get; set; }
        public int m1007_cod { get; set; }
        public string a1006_signo { get; set; }
        public Nullable<decimal> a1006_impdiv { get; set; }
        public Nullable<decimal> a1006_camdiv { get; set; }
        public Nullable<decimal> a1006_import { get; set; }
        public string a1006_coment { get; set; }
        public string a1006_numdoc { get; set; }
        public System.DateTime a1005_diari { get; set; }
        public Nullable<System.DateTime> a1006_fecval { get; set; }
        public string m1015_cod { get; set; }
        public string m1036_codcon { get; set; }
        public string m1011_cod { get; set; }
        public string a1001_codctp { get; set; }
        public int a1005_numint { get; set; }
        public int a1006_numint { get; set; }
        public Nullable<int> a1006_numope { get; set; }
        public string m1036_codana { get; set; }
        public string a1006_refaux { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> a1006_datcre { get; set; }
        public string a1006_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> a1006_datmod { get; set; }
        public string a1006_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public string m1012_cod { get; set; }
        public Nullable<int> m2001_cod { get; set; }
    }
}
