//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b1001
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public b1001()
        {
            this.b2004 = new HashSet<b2004>();
            this.b4051 = new HashSet<b4051>();
        }
    
        public string b1001_tipcod { get; set; }
        public string b1001_cod { get; set; }
        public string b1001_tipper { get; set; }
        public string b1001_nif { get; set; }
        public Nullable<System.DateTime> b1001_datnac { get; set; }
        public string b1001_nomcom { get; set; }
        public string b1001_nom { get; set; }
        public string b1001_ap1 { get; set; }
        public string b1001_ap2 { get; set; }
        public string m1058_idioma { get; set; }
        public string b1001_obs { get; set; }
        public bool b1001_inc { get; set; }
        public string b1058_cod { get; set; }
        public string b1056_cod { get; set; }
        public bool b1001_envmai { get; set; }
        public Nullable<int> b1003_nummai { get; set; }
        public bool b1001_pterev { get; set; }
        public string b2056_cod { get; set; }
        public string b1001_sexo { get; set; }
        public string m1027_cod { get; set; }
        public bool b1001_activo { get; set; }
        public Nullable<System.DateTime> b1001_datcad { get; set; }
        public string b1001_codext { get; set; }
        public string m1009_codnac { get; set; }
        public byte b1001_reside { get; set; }
        public Nullable<System.DateTime> b1001_datdni { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b1001_datcre { get; set; }
        public string b1001_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b1001_datmod { get; set; }
        public string b1001_hormod { get; set; }
        public bool b1001_estper { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public Nullable<System.DateTime> b1001_datalt { get; set; }
        public bool b1001_retenc { get; set; }
        public string b1001_tcodif { get; set; }
        public string m1036_cod { get; set; }
        public string b1001_numdoc { get; set; }
        public bool b1001_fongan { get; set; }
        public Nullable<System.DateTime> b1001_datfret { get; set; }
        public string m1009_codnai { get; set; }
        public Nullable<System.DateTime> b1001_datiret { get; set; }
        public Nullable<System.DateTime> b1001_datcer { get; set; }
        public string m1027_ciunac { get; set; }
        public string b1001_tipdoc { get; set; }
        public string b1001_obsret { get; set; }
        public string b1001_motfon { get; set; }
        public string b1001_cicvta { get; set; }
        public string b1001_tipser { get; set; }
        public string b1001_not { get; set; }
        public string b3068_cod { get; set; }
        public string m4050_lisnum { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public Nullable<bool> b1001_lisrob { get; set; }
        public Nullable<System.DateTime> b1001_datrob { get; set; }
        public byte b1001_clifin { get; set; }
        public byte b1001_ordena { get; set; }
        public string b1001_cirete { get; set; }
        public string b1001_modd6 { get; set; }
        public string b1001_mod720 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b2004> b2004 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b4051> b4051 { get; set; }
    }
}
