//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b3006
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public b3006()
        {
            this.b3017 = new HashSet<b3017>();
        }
    
        public string b3006_cod { get; set; }
        public string b3006_tipsub { get; set; }
        public string b3006_nom { get; set; }
        public string b3006_nomred { get; set; }
        public string b3006_codsub { get; set; }
        public decimal b3006_tpcgar { get; set; }
        public decimal b3006_fijgar { get; set; }
        public string b3006_subssb { get; set; }
        public string b3006_subiom { get; set; }
        public string b3006_mb3 { get; set; }
        public string b3006_codmef { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b3006_datcre { get; set; }
        public string b3006_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b3006_datmod { get; set; }
        public string b3006_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public string b3006_codsch { get; set; }
        public string b3006_detcom { get; set; }
        public string b3006_origen { get; set; }
        public string b3006_vto { get; set; }
        public string b3006_tipcom { get; set; }
        public decimal b3006_multip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b3017> b3017 { get; set; }
    }
}
