//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b3001
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public b3001()
        {
            this.b3002 = new HashSet<b3002>();
            this.b3040 = new HashSet<b3040>();
            this.b5001 = new HashSet<b5001>();
            this.b5004 = new HashSet<b5004>();
        }
    
        public string b3001_cod { get; set; }
        public string b3001_tipcod { get; set; }
        public bool b3001_provis { get; set; }
        public string b3001_nom { get; set; }
        public string b3001_nomcom { get; set; }
        public string b3001_codbe { get; set; }
        public string b3001_tvdgte { get; set; }
        public Nullable<int> b3050_cod { get; set; }
        public string b3062_cod { get; set; }
        public string b3056_cod { get; set; }
        public string b3001_orireg { get; set; }
        public string b3001_cotiza { get; set; }
        public Nullable<System.DateTime> b3001_datini { get; set; }
        public int b3001_numdec { get; set; }
        public string b3058_cod { get; set; }
        public string b2054_codctp { get; set; }
        public bool b3001_valinc { get; set; }
        public string b3001_quefal { get; set; }
        public string b3056_extval { get; set; }
        public string b3056_clains { get; set; }
        public bool b3001_recpte { get; set; }
        public string b3052_liscod { get; set; }
        public string b3002_liscdm { get; set; }
        public string b3080_liscod { get; set; }
        public bool b3001_gastos { get; set; }
        public bool b3001_revpte { get; set; }
        public string b3001_clasec { get; set; }
        public bool b3001_valcar { get; set; }
        public bool b3001_valvar { get; set; }
        public Nullable<System.DateTime> b3001_datvar { get; set; }
        public bool b3001_novolc { get; set; }
        public bool b3001_calest { get; set; }
        public Nullable<System.DateTime> b3001_datest { get; set; }
        public bool b3001_carliq { get; set; }
        public bool b3001_fis { get; set; }
        public string b3001_codref { get; set; }
        public bool b3001_llevan { get; set; }
        public bool b3001_fisic { get; set; }
        public Nullable<System.DateTime> b3001_datvto { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b3001_datcre { get; set; }
        public string b3001_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b3001_datmod { get; set; }
        public string b3001_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public bool b3001_nofact { get; set; }
        public decimal b3001_tpcpro { get; set; }
        public string m1009_codret { get; set; }
        public decimal b3001_tpctra { get; set; }
        public string b3059_cod { get; set; }
        public string b3037_result { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public string b3001_coddep { get; set; }
        public string b3094_cod { get; set; }
        public bool b3001_movcar { get; set; }
        public string b3001_aii { get; set; }
        public string b3059_disliq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b3002> b3002 { get; set; }
        public virtual b3017 b3017 { get; set; }
        public virtual b3022 b3022 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b3040> b3040 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b5001> b5001 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b5004> b5004 { get; set; }
    }
}
