//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b3022
    {
        public string b3001_cod { get; set; }
        public System.DateTime b3022_datemi { get; set; }
        public Nullable<System.DateTime> b3022_datdev { get; set; }
        public Nullable<System.DateTime> b3022_datvto { get; set; }
        public decimal b3022_valnom { get; set; }
        public string m1015_cod { get; set; }
        public string b3022_tipcup { get; set; }
        public byte b3022_multic { get; set; }
        public byte b3022_conver { get; set; }
        public string b3066_cod { get; set; }
        public decimal b3022_sprcup { get; set; }
        public decimal b3022_floor { get; set; }
        public decimal b3022_cap { get; set; }
        public decimal b3022_cupon { get; set; }
        public string b3022_percup { get; set; }
        public int b3022_base { get; set; }
        public string b3022_tipint { get; set; }
        public decimal b3022_priemi { get; set; }
        public decimal b3022_priamo { get; set; }
        public byte b3022_retenc { get; set; }
        public Nullable<System.DateTime> b3022_datcal { get; set; }
        public decimal b3022_strcal { get; set; }
        public Nullable<System.DateTime> b3022_datput { get; set; }
        public decimal b3022_strput { get; set; }
        public string b3022_sp { get; set; }
        public string b3022_moodys { get; set; }
        public string b3022_fitibc { get; set; }
        public decimal b3022_prodef { get; set; }
        public string b3001_codref { get; set; }
        public decimal b3022_sprref { get; set; }
        public decimal b3022_volemi { get; set; }
        public string b3056_cod { get; set; }
        public string b3022_des { get; set; }
        public string b3022_tirblo { get; set; }
        public byte b3022_cotexc { get; set; }
        public Nullable<System.DateTime> b3022_datpcu { get; set; }
        public string b3022_dtocap { get; set; }
        public byte b3022_segre { get; set; }
        public int b3022_bascup { get; set; }
        public byte b3022_retjur { get; set; }
        public Nullable<System.DateTime> b3022_dattpi { get; set; }
        public string b3022_pertpi { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b3022_datcre { get; set; }
        public string b3022_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b3022_datmod { get; set; }
        public string b3022_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public byte b3022_retamo { get; set; }
        public Nullable<decimal> b3022_nomini { get; set; }
        public decimal b3022_tpcbon { get; set; }
        public string m1015_codini { get; set; }
        public decimal b3022_sprcur { get; set; }
        public string b3069_cod { get; set; }
        public string b3022_cupcor { get; set; }
        public int b3022_diaval { get; set; }
        public string b3022_tipcor { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public string b3022_claent { get; set; }
        public byte b3022_segreo { get; set; }
        public bool b3022_avains { get; set; }
        public string b3085_codfac { get; set; }
        public string b3069_codspr { get; set; }
        public bool b3022_sinmse { get; set; }
        public decimal b3022_basipc { get; set; }
        public string b3001_codfrn { get; set; }
    
        public virtual b3001 b3001 { get; set; }
        public virtual b3085 b3085 { get; set; }
    }
}
