//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b3085
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public b3085()
        {
            this.b2001 = new HashSet<b2001>();
            this.b3022 = new HashSet<b3022>();
            this.b3089 = new HashSet<b3089>();
        }
    
        public string b3085_cod { get; set; }
        public string b3085_nom { get; set; }
        public string b3085_obs { get; set; }
        public string b3001_codref1 { get; set; }
        public string b3001_codref2 { get; set; }
        public string b3001_codref3 { get; set; }
        public string b3001_codref4 { get; set; }
        public string b3001_codref5 { get; set; }
        public decimal b3085_spread1 { get; set; }
        public decimal b3085_spread2 { get; set; }
        public decimal b3085_spread3 { get; set; }
        public decimal b3085_spread4 { get; set; }
        public decimal b3085_spread5 { get; set; }
        public decimal b3085_pesrel1 { get; set; }
        public decimal b3085_pesrel2 { get; set; }
        public decimal b3085_pesrel3 { get; set; }
        public decimal b3085_pesrel4 { get; set; }
        public decimal b3085_pesrel5 { get; set; }
        public decimal b3085_pesabs { get; set; }
        public string m1008_codcre { get; set; }
        public System.DateTime b3085_datcre { get; set; }
        public string b3085_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public System.DateTime b3085_datmod { get; set; }
        public string b3085_hormod { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public byte b3085_cotcon5 { get; set; }
        public byte b3085_cotcon4 { get; set; }
        public byte b3085_cotcon3 { get; set; }
        public byte b3085_cotcon2 { get; set; }
        public byte b3085_cotcon1 { get; set; }
        public byte b3085_cotcon10 { get; set; }
        public decimal b3085_spread10 { get; set; }
        public string b3001_codref10 { get; set; }
        public decimal b3085_spread9 { get; set; }
        public decimal b3085_spread8 { get; set; }
        public decimal b3085_pesrel10 { get; set; }
        public decimal b3085_spread7 { get; set; }
        public decimal b3085_spread6 { get; set; }
        public string b3001_codref9 { get; set; }
        public string b3001_codref8 { get; set; }
        public string b3001_codref7 { get; set; }
        public string b3001_codref6 { get; set; }
        public byte b3085_cotcon9 { get; set; }
        public byte b3085_cotcon8 { get; set; }
        public byte b3085_cotcon7 { get; set; }
        public byte b3085_cotcon6 { get; set; }
        public decimal b3085_pesrel9 { get; set; }
        public decimal b3085_pesrel8 { get; set; }
        public decimal b3085_pesrel7 { get; set; }
        public decimal b3085_pesrel6 { get; set; }
        public string b3085_des { get; set; }
        public bool b3085_inf { get; set; }
        public System.DateTime b3085_datini { get; set; }
        public byte b3085_calpor9 { get; set; }
        public byte b3085_calpor8 { get; set; }
        public byte b3085_calpor7 { get; set; }
        public byte b3085_calpor6 { get; set; }
        public byte b3085_calpor5 { get; set; }
        public byte b3085_calpor4 { get; set; }
        public byte b3085_calpor3 { get; set; }
        public byte b3085_calpor2 { get; set; }
        public byte b3085_calpor1 { get; set; }
        public byte b3085_calpor10 { get; set; }
        public string b3085_tip { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b2001> b2001 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b3022> b3022 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b3089> b3089 { get; set; }
    }
}
