//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b3089
    {
        public string b3085_cod { get; set; }
        public System.DateTime b3089_dat { get; set; }
        public decimal b3089_cotiza { get; set; }
        public string m1015_cod { get; set; }
        public string m1008_codcre { get; set; }
        public System.DateTime b3089_datcre { get; set; }
        public string b3089_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public System.DateTime b3089_datmod { get; set; }
        public string b3089_hormod { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public decimal b3089_ren { get; set; }
        public decimal b3089_var { get; set; }
        public decimal b3089_sharpe { get; set; }
        public decimal b3089_vol { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    
        public virtual b3085 b3085 { get; set; }
    }
}
