//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b4002
    {
        public int b4051_cod { get; set; }
        public Nullable<System.DateTime> b4002_dat { get; set; }
        public string a1001_cod1 { get; set; }
        public string a1001_cod2 { get; set; }
        public decimal b4002_impdeb { get; set; }
        public decimal b4002_imphab { get; set; }
        public string b4002_des { get; set; }
        public int a1006_numint { get; set; }
        public string b4002_tipmov { get; set; }
        public string b4002_origen { get; set; }
        public string b3001_cod { get; set; }
        public byte b4002_pos { get; set; }
        public Nullable<int> b5004_num { get; set; }
        public byte b5004_liq { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b4002_datcre { get; set; }
        public string b4002_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b4002_datmod { get; set; }
        public string b4002_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public string m1015_codhab { get; set; }
        public string m1015_coddeb { get; set; }
        public Nullable<decimal> b4002_camhab { get; set; }
        public decimal b4002_camdeb { get; set; }
        public int b4002_recid { get; set; }
        public int b4064_cod { get; set; }
        public Nullable<int> b5001_num { get; set; }
        public string b5052_cod { get; set; }
        public string a1001_codcp2 { get; set; }
        public string a1001_codcp1 { get; set; }
    }
}
