//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b4001
    {
        public int b4051_cod { get; set; }
        public System.DateTime b4001_dat { get; set; }
        public decimal b4001_valliq { get; set; }
        public decimal b4001_valcot { get; set; }
        public decimal b4001_partic { get; set; }
        public decimal b4001_numpar { get; set; }
        public decimal b4001_paralt { get; set; }
        public decimal b4001_parbaj { get; set; }
        public decimal b4001_patrim { get; set; }
        public decimal b4001_patri2 { get; set; }
        public decimal b4001_activo { get; set; }
        public decimal b4001_accpro { get; set; }
        public decimal b4001_valcar { get; set; }
        public decimal b4001_valcai { get; set; }
        public decimal b4001_dispon { get; set; }
        public decimal b4001_coeliq { get; set; }
        public decimal b4001_renhis { get; set; }
        public decimal b4001_volhis { get; set; }
        public decimal b4001_errtra { get; set; }
        public decimal b4001_impsus { get; set; }
        public decimal b4001_imprem { get; set; }
        public decimal b4001_impint { get; set; }
        public decimal b4001_impdiv { get; set; }
        public decimal b4001_impder { get; set; }
        public decimal b4001_impvpr { get; set; }
        public decimal b4001_iresdv { get; set; }
        public decimal b4001_iotren { get; set; }
        public decimal b4001_icomge { get; set; }
        public decimal b4001_icomde { get; set; }
        public decimal b4001_impcor { get; set; }
        public decimal b4001_impser { get; set; }
        public decimal b4001_implat { get; set; }
        public decimal b4001_gasfij { get; set; }
        public decimal b4001_ingfij { get; set; }
        public decimal b4001_comisi { get; set; }
        public decimal b4001_tas { get; set; }
        public decimal b4001_impues { get; set; }
        public decimal b4001_reejan { get; set; }
        public decimal b4001_gastos { get; set; }
        public decimal b4001_ingres { get; set; }
        public decimal b4001_plulat { get; set; }
        public decimal b4001_impspl { get; set; }
        public decimal b4001_lucces { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b4001_datcre { get; set; }
        public string b4001_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b4001_datmod { get; set; }
        public string b4001_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public bool b4001_valest { get; set; }
        public Nullable<System.DateTime> b4001_datope { get; set; }
        public Nullable<System.DateTime> b4001_datval { get; set; }
        public Nullable<decimal> b4001_durcar { get; set; }
        public Nullable<decimal> b4001_tpcder { get; set; }
        public string b4001_notas { get; set; }
        public Nullable<decimal> b4001_bet { get; set; }
        public Nullable<decimal> b4001_var { get; set; }
        public decimal b4001_valref { get; set; }
        public string m1008_codvali { get; set; }
        public Nullable<System.DateTime> b4001_datvali { get; set; }
        public string b4001_horvali { get; set; }
        public string m1036_codvali { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public Nullable<decimal> b4001_capini { get; set; }
        public Nullable<decimal> b4001_autnom { get; set; }
        public Nullable<decimal> b4001_estmax { get; set; }
        public Nullable<decimal> b4001_estemi { get; set; }
        public decimal b4001_resleg { get; set; }
        public decimal b4001_capcir { get; set; }
        public string m1036_codpar { get; set; }
        public decimal b4001_capres { get; set; }
        public decimal b4001_beg { get; set; }
        public decimal b4001_minleg { get; set; }
        public decimal b4001_cappdt { get; set; }
        public decimal b4001_patrvl { get; set; }
        public decimal b4001_resdis { get; set; }
        public decimal b4001_patrid { get; set; }
        public decimal b4001_numpad { get; set; }
    }
}
