//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b5006
    {
        public string m1015_cod { get; set; }
        public string b3001_cod { get; set; }
        public string b3052_cod { get; set; }
        public System.DateTime b5006_dat { get; set; }
        public decimal b5006_cosmed { get; set; }
        public decimal b5006_cantid { get; set; }
        public Nullable<System.DateTime> b5006_datcom { get; set; }
        public Nullable<System.DateTime> b5006_datope { get; set; }
        public byte b5006_caltco { get; set; }
        public decimal b5006_cupcor { get; set; }
        public decimal b5006_tircom { get; set; }
        public byte b5006_cobert { get; set; }
        public string b3001_codcob { get; set; }
        public decimal b5006_impcob { get; set; }
        public string m1015_codcob { get; set; }
        public decimal b5006_nomina { get; set; }
        public Nullable<System.DateTime> b5006_datvto { get; set; }
        public decimal b5006_intere { get; set; }
        public decimal b5006_plusva { get; set; }
        public decimal b5006_valact { get; set; }
        public decimal b5006_camval { get; set; }
        public decimal b5006_efeact { get; set; }
        public string m1008_codcre { get; set; }
        public decimal b5006_efecos { get; set; }
        public decimal b5006_efcodi { get; set; }
        public int b5018_num { get; set; }
        public Nullable<System.DateTime> b5006_datcre { get; set; }
        public string b5006_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b5006_datmod { get; set; }
        public string b5006_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public int b3050_cod { get; set; }
        public int b4064_cod { get; set; }
        public string b5006_conden { get; set; }
        public Nullable<System.DateTime> b5006_vtosub { get; set; }
        public decimal b5006_contra { get; set; }
        public string b5006_codsub { get; set; }
        public decimal b5006_poslar { get; set; }
        public decimal b5006_durfic { get; set; }
        public decimal b5006_preeje { get; set; }
        public decimal b5006_poscor { get; set; }
        public string m1015_codsub { get; set; }
        public string b5006_rating { get; set; }
        public string b5006_subyac { get; set; }
        public string b5006_idcode { get; set; }
        public decimal b5006_conliq { get; set; }
        public decimal b5006_garan { get; set; }
        public string b5006_codgar { get; set; }
        public decimal b5006_delta { get; set; }
        public decimal b5006_valsub { get; set; }
        public int b8070_num { get; set; }
        public decimal b5006_cancob { get; set; }
        public decimal b5006_duraci { get; set; }
        public decimal b5006_dursub { get; set; }
        public int b5006_orden { get; set; }
        public decimal b5006_difcup { get; set; }
        public string b5006_tip { get; set; }
        public string b5006_obs { get; set; }
        public string b2054_coddep { get; set; }
        public decimal b5006_acumbe { get; set; }
        public decimal b5006_acumpe { get; set; }
    }
}
