//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b5001
    {
        public Nullable<int> b5001_num { get; set; }
        public int m1006_cod { get; set; }
        public string b2050_cod { get; set; }
        public string b2001_cod { get; set; }
        public string m1015_cod { get; set; }
        public string b5001_clamov { get; set; }
        public string b5052_cod { get; set; }
        public string b5001_nom { get; set; }
        public string b5001_coment { get; set; }
        public string b5001_comen2 { get; set; }
        public string b5001_refer { get; set; }
        public System.DateTime b5001_datope { get; set; }
        public System.DateTime b5001_datval { get; set; }
        public decimal b5001_impcta { get; set; }
        public decimal b5001_impori { get; set; }
        public Nullable<decimal> b5001_impaux { get; set; }
        public decimal b5001_impgas { get; set; }
        public Nullable<int> m1006_codtes { get; set; }
        public string a4003_cdites { get; set; }
        public string b5001_ctadom { get; set; }
        public string b5001_efecto { get; set; }
        public Nullable<int> b5003_num { get; set; }
        public string m1011_cod { get; set; }
        public Nullable<System.DateTime> b5001_datcon { get; set; }
        public Nullable<int> a1005_numint { get; set; }
        public Nullable<int> a1006_numint { get; set; }
        public string m1036_cod { get; set; }
        public string b2056_cod { get; set; }
        public string b5001_brunet { get; set; }
        public Nullable<decimal> b5001_nparti { get; set; }
        public string b3001_cod { get; set; }
        public string b5013_mer { get; set; }
        public string b5001_efectu { get; set; }
        public string b5001_boleti { get; set; }
        public Nullable<int> b5001_numanu { get; set; }
        public string b3052_cod { get; set; }
        public string b2054_coddep { get; set; }
        public decimal b5001_basret { get; set; }
        public decimal b5001_tpcret { get; set; }
        public Nullable<decimal> b5001_impret { get; set; }
        public byte b5001_declar { get; set; }
        public decimal b5001_tpciva { get; set; }
        public decimal b5001_impiva { get; set; }
        public decimal b5001_basiva { get; set; }
        public byte b5001_provis { get; set; }
        public string b5001_origen { get; set; }
        public Nullable<System.DateTime> b5001_datses { get; set; }
        public Nullable<int> b5004_num { get; set; }
        public byte b5001_concil { get; set; }
        public decimal b5001_cambio { get; set; }
        public Nullable<int> b5015_num { get; set; }
        public Nullable<int> a1053_numint { get; set; }
        public Nullable<System.DateTime> b5001_dattra { get; set; }
        public decimal b5001_retori { get; set; }
        public decimal b5001_cdtfis { get; set; }
        public byte b5001_salini { get; set; }
        public Nullable<byte> b5001_liqiic { get; set; }
        public Nullable<int> m9915_num { get; set; }
        public string b5001_nacint { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b5001_datcre { get; set; }
        public string b5001_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b5001_datmod { get; set; }
        public string b5001_hormod { get; set; }
        public Nullable<byte> b5001_canpar { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public byte b5052_coresp { get; set; }
        public byte b5052_ingadm { get; set; }
        public Nullable<int> a1005_numope { get; set; }
        public Nullable<int> b5001_numori { get; set; }
        public string b5001_banco { get; set; }
        public string m1009_codban { get; set; }
        public Nullable<decimal> b5001_impliq { get; set; }
        public Nullable<int> m9915_numenv { get; set; }
        public Nullable<int> b5001_numiic { get; set; }
        public Nullable<byte> b5052_modman { get; set; }
        public Nullable<byte> b5052_invdes { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public string b5001_serie { get; set; }
        public Nullable<int> b5001_numfac { get; set; }
        public Nullable<int> b3040_num { get; set; }
        public Nullable<int> b8070_num { get; set; }
        public Nullable<int> b5001_numpri { get; set; }
        public Nullable<int> m1006_codsin { get; set; }
        public string m1015_codsin { get; set; }
        public string b2050_codsin { get; set; }
        public string b2001_codsin { get; set; }
        public Nullable<decimal> b5001_camcta { get; set; }
        public string b5001_codbic { get; set; }
        public string b5001_obs { get; set; }
        public string b5001_nomcon { get; set; }
    
        public virtual b2001 b2001 { get; set; }
        public virtual b3001 b3001 { get; set; }
        public virtual b3040 b3040 { get; set; }
    }
}
