//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraVentaPrecAdq_Added
    {
        public string CodigoIC { get; set; }
        public string IsinPlantilla { get; set; }
        public string Isin { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Titulos { get; set; }
        public string DescripcionValor { get; set; }
        public Nullable<decimal> Adquisicion { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
    }
}
