//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Errore
    {
        public int Id { get; set; }
        public Nullable<int> CodigoError { get; set; }
        public string Error { get; set; }
        public string CodigoIC { get; set; }
        public Nullable<System.DateTime> FechaGeneracionInforme { get; set; }
        public System.DateTime FechaError { get; set; }
        public string Equipo { get; set; }
    }
}
