//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrumento()
        {
            this.IndicesPreconfiguradosNovarexes = new HashSet<IndicesPreconfiguradosNovarex>();
            this.Instrumentos_Importados = new HashSet<Instrumentos_Importados>();
            this.Parametros_Diversificacion_Instrumentos = new HashSet<Parametros_Diversificacion_Instrumentos>();
            this.Temp_Diversificacion = new HashSet<Temp_Diversificacion>();
            this.Temp_GraficoExposMercTipoActivo = new HashSet<Temp_GraficoExposMercTipoActivo>();
            this.Temp_GraficoCompPatrimonioTipoProducto = new HashSet<Temp_GraficoCompPatrimonioTipoProducto>();
            this.Temp_RentaFija = new HashSet<Temp_RentaFija>();
        }
    
        public string Id { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicesPreconfiguradosNovarex> IndicesPreconfiguradosNovarexes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instrumentos_Importados> Instrumentos_Importados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_Diversificacion_Instrumentos> Parametros_Diversificacion_Instrumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Diversificacion> Temp_Diversificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_GraficoExposMercTipoActivo> Temp_GraficoExposMercTipoActivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_GraficoCompPatrimonioTipoProducto> Temp_GraficoCompPatrimonioTipoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_RentaFija> Temp_RentaFija { get; set; }
    }
}
