//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrumentos_Tipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrumentos_Tipos()
        {
            this.Instrumentos_Importados = new HashSet<Instrumentos_Importados>();
            this.Instrumentos_Importados1 = new HashSet<Instrumentos_Importados>();
            this.Instrumentos_Importados2 = new HashSet<Instrumentos_Importados>();
            this.Plantillas_Estrategias = new HashSet<Plantillas_Estrategias>();
            this.Temp_GraficoCompPatrimonioTipoProducto = new HashSet<Temp_GraficoCompPatrimonioTipoProducto>();
            this.Temp_RentaFija = new HashSet<Temp_RentaFija>();
        }
    
        public string Id { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instrumentos_Importados> Instrumentos_Importados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instrumentos_Importados> Instrumentos_Importados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instrumentos_Importados> Instrumentos_Importados2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Estrategias> Plantillas_Estrategias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_GraficoCompPatrimonioTipoProducto> Temp_GraficoCompPatrimonioTipoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_RentaFija> Temp_RentaFija { get; set; }
    }
}
