//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class m1016
    {
        public string m1015_codori { get; set; }
        public string m1015_codbas { get; set; }
        public int m1016_canori { get; set; }
        public int m1016_canbas { get; set; }
        public System.DateTime m1016_dat { get; set; }
        public decimal m1016_preven { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> m1016_datcre { get; set; }
        public string m1016_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> m1016_datmod { get; set; }
        public string m1016_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public string m1016_fuente { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
