//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_Diversificacion_Instrumentos_Divisas
    {
        public int Id { get; set; }
        public int IdParametroDiversificacionIntrumento { get; set; }
        public int IdDivisa { get; set; }
    
        public virtual Instrumentos_Divisas Instrumentos_Divisas { get; set; }
        public virtual Parametros_Diversificacion_Instrumentos Parametros_Diversificacion_Instrumentos { get; set; }
    }
}
