//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_PlusvaliasDividendos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parametros_PlusvaliasDividendos()
        {
            this.Parametros_PlusvaliasDividendos_ISINS = new HashSet<Parametros_PlusvaliasDividendos_ISINS>();
        }
    
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_PlusvaliasDividendos_ISINS> Parametros_PlusvaliasDividendos_ISINS { get; set; }
        public virtual Plantilla Plantilla { get; set; }
    }
}
