//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_IndicePreconfiguradoNovarex_Otros
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string IndiceRvOtros { get; set; }
        public string IndiceRfOtros { get; set; }
        public string IndiceRepoTesDepOtros { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
