//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipesSalat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipesSalat()
        {
            this.ParticipesSalat_Aportaciones = new HashSet<ParticipesSalat_Aportaciones>();
            this.ParticipesSalat_Participes = new HashSet<ParticipesSalat_Participes>();
            this.ParticipesSalat_Periodos = new HashSet<ParticipesSalat_Periodos>();
        }
    
        public int Id { get; set; }
        public string TituloInforme { get; set; }
        public string EvolucionCarteras_Text { get; set; }
        public string Aportaciones_EvolCart_Text { get; set; }
        public string Valor_EvolCart_Text { get; set; }
        public Nullable<decimal> Valor_EvolCartera { get; set; }
        public string TotalPeriodos_Text { get; set; }
        public Nullable<decimal> TotalPeriodos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipesSalat_Aportaciones> ParticipesSalat_Aportaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipesSalat_Participes> ParticipesSalat_Participes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipesSalat_Periodos> ParticipesSalat_Periodos { get; set; }
    }
}
