//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipesSalat_Periodos_Lineas
    {
        public int Id { get; set; }
        public int IdParticipesSalatPeriodo { get; set; }
        public int IdTitular { get; set; }
        public string Titular { get; set; }
        public Nullable<decimal> ImporteInvertido { get; set; }
        public decimal Valor { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public decimal Resultado { get; set; }
        public Nullable<decimal> ValorMasEfectPeriodoAnt { get; set; }
        public int IdParametroParticipeSalat { get; set; }
    
        public virtual ParticipesSalat_Participes ParticipesSalat_Participes { get; set; }
        public virtual ParticipesSalat_Periodos ParticipesSalat_Periodos { get; set; }
    }
}
