//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipesSalat_Periodos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipesSalat_Periodos()
        {
            this.ParticipesSalat_Periodos_Lineas = new HashSet<ParticipesSalat_Periodos_Lineas>();
        }
    
        public int Id { get; set; }
        public int IdTempParticipeSalat { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaSaldo { get; set; }
    
        public virtual ParticipesSalat ParticipesSalat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipesSalat_Periodos_Lineas> ParticipesSalat_Periodos_Lineas { get; set; }
    }
}
