//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_12_Table
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string Isin { get; set; }
        public Nullable<decimal> Rentabilidad { get; set; }
        public Nullable<decimal> TotalPatrimonio { get; set; }
        public Nullable<decimal> TotalParticipaciones { get; set; }
        public Nullable<decimal> ValorLiquidativo { get; set; }
        public Nullable<decimal> TAE { get; set; }
        public Nullable<decimal> SaldoTesoreria { get; set; }
        public Nullable<decimal> ActivoComputable { get; set; }
    }
}
