//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentaVariable_Equivalencias
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string IsinDerechos { get; set; }
        public string OldIsin { get; set; }
        public string NewIsin { get; set; }
        public Nullable<decimal> FactorAjuste { get; set; }
        public Nullable<System.DateTime> FechaIniDerechos { get; set; }
        public Nullable<System.DateTime> FechaEquiparacion { get; set; }
        public Nullable<System.DateTime> FechaSuscripcion { get; set; }
        public string TipoOperacion { get; set; }
    }
}
