//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentabilidadCarteraSolemeg
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string ISIN { get; set; }
        public string Descripcion { get; set; }
        public decimal NumeroTitulos { get; set; }
        public Nullable<decimal> PrecioCompraOriginal { get; set; }
        public Nullable<decimal> PrecioCompraSolemeg { get; set; }
        public Nullable<decimal> PrecioActual { get; set; }
        public bool Vendido { get; set; }
        public int Grupo { get; set; }
        public string Mercado { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
