//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentabilidadIndiceNovarex
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> ValorLiquidativo { get; set; }
        public decimal RentabilidadAcumulada { get; set; }
    }
}
