//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeccionesParametro
    {
        public int IdSeccionParametro { get; set; }
        public Nullable<int> IdSeccion { get; set; }
        public string CodigoIc { get; set; }
        public string NombreParametro { get; set; }
        public string ValorParametro { get; set; }
    }
}
