//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_VariacionPatrimonialA
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string IsinPlantilla { get; set; }
        public string CodsInstrumento { get; set; }
        public string CodsTipoInstrumento { get; set; }
        public string CodsCategoria { get; set; }
        public string CodsEmpresa { get; set; }
        public Nullable<decimal> Cartera { get; set; }
        public Nullable<decimal> Ventas { get; set; }
        public Nullable<decimal> BoPPrecio { get; set; }
        public Nullable<decimal> BoPDivisa { get; set; }
        public Nullable<decimal> TotalPrecios { get; set; }
        public Nullable<decimal> Cobrados { get; set; }
        public Nullable<decimal> DevengadosPtesCobrar { get; set; }
        public Nullable<decimal> TotalIngresos { get; set; }
        public Nullable<decimal> Otros { get; set; }
        public bool TieneBordeSuperior { get; set; }
        public bool TieneBordeInferior { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
