//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_DistribucionPatrimonioNovarex_Cartera
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public decimal RentaVariable { get; set; }
        public decimal RentaVariablePorc { get; set; }
        public decimal RepoDeuda { get; set; }
        public decimal RepoDeudaPorc { get; set; }
        public decimal RentaFija { get; set; }
        public decimal RentaFijaPorc { get; set; }
        public Nullable<decimal> RetornoAbsoluto { get; set; }
        public Nullable<decimal> RetornoAbsolutoPorc { get; set; }
        public Nullable<decimal> GarantizadosEstructurados { get; set; }
        public Nullable<decimal> GarantizadosEstructuradosPorc { get; set; }
        public Nullable<decimal> Otros { get; set; }
        public Nullable<decimal> OtrosPorc { get; set; }
        public decimal TotalPatrimonio { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
