//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_DesgloseGastos
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string Isin { get; set; }
        public decimal ComFijaPagada { get; set; }
        public decimal ComFijaDevengada { get; set; }
        public decimal ComVariable { get; set; }
        public decimal ComDepositario { get; set; }
        public decimal GastosTasaRegistrosOficiales { get; set; }
        public decimal GastosAdmisionCotizacionBolsa { get; set; }
        public decimal GastosDiferenciaPeriodificaciones { get; set; }
        public decimal GastosBancarios { get; set; }
        public decimal GastosRegistroLibroAccionistas { get; set; }
        public decimal AuditoriaCuentas { get; set; }
        public decimal Otros { get; set; }
        public decimal ImpuestoSobreSociedades { get; set; }
        public decimal PatrimonioFechaInforme { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
