//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_RentaVariable
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string IsinPlantilla { get; set; }
        public string Isin { get; set; }
        public string Descripcion { get; set; }
        public string Grupo { get; set; }
        public Nullable<int> GrupoNuevo { get; set; }
        public Nullable<decimal> NumTit { get; set; }
        public Nullable<decimal> PrecioIni { get; set; }
        public Nullable<decimal> PrecioAjustado { get; set; }
        public Nullable<decimal> PrecioFin { get; set; }
        public Nullable<decimal> PrecioFinEuros { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public string IdInstrumento { get; set; }
        public string IdTipoInstrumento { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<decimal> BoPDivisa { get; set; }
        public Nullable<decimal> BoPPrecio { get; set; }
        public Nullable<decimal> BoPDividendos { get; set; }
        public Nullable<decimal> BoPTotal { get; set; }
        public Nullable<decimal> BoPTotalPorcentaje { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<decimal> PosicionCartera { get; set; }
        public Nullable<decimal> PosicionesCerradas { get; set; }
        public string CodigoSubyacente { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> CambioC { get; set; }
        public Nullable<decimal> CambioF { get; set; }
        public Nullable<decimal> CambioI { get; set; }
        public Nullable<decimal> CambioO { get; set; }
        public Nullable<decimal> TipoCambioIni { get; set; }
        public Nullable<decimal> TipoCambioFin { get; set; }
        public Nullable<long> NumO { get; set; }
        public Nullable<int> IdPrecioAjustado { get; set; }
        public Nullable<decimal> PrecioC { get; set; }
        public Nullable<decimal> PrecioF { get; set; }
        public Nullable<decimal> PrecioFEUR { get; set; }
        public Nullable<decimal> PrecioI { get; set; }
        public Nullable<decimal> PrecioO { get; set; }
        public Nullable<decimal> PrecioOA { get; set; }
        public string TipoO { get; set; }
        public Nullable<long> NumC { get; set; }
        public string TipoC { get; set; }
    }
}
