//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Diversificacion
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string Isin { get; set; }
        public string IdInstrumento { get; set; }
        public Nullable<int> IdDivisa { get; set; }
        public string DivisaDesc { get; set; }
        public decimal Patrimonio { get; set; }
        public decimal PorcentajeGrupo { get; set; }
        public decimal PorcentajeP { get; set; }
    
        public virtual Instrumento Instrumento { get; set; }
        public virtual Instrumentos_Divisas Instrumentos_Divisas { get; set; }
    }
}
