//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariacionPatrimonial_Cuentas
    {
        public string Descripcion { get; set; }
        public string CuentasVariacionPrecios { get; set; }
        public string CuentasIngresosFinancieros { get; set; }
        public string CuentasOtrosRendimientos { get; set; }
    }
}
