//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reports_IICs.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Aceptar_Button {
            get {
                return ResourceManager.GetString("Aceptar_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuadre entre dividendos cobrados y el &quot;TOTAL INGRESOS FINANCIEROS&quot; de RV (VARIACIÓN PATRIMONIAL A): {0:N2}..
        /// </summary>
        public static string AlertaDivCobIngrFinanRV {
            get {
                return ResourceManager.GetString("AlertaDivCobIngrFinanRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El saldo de la cuenta 7600002 (Ingresos fin. participaciones ext.) es: {0:N2}..
        /// </summary>
        public static string AlertaDividendosCobradosCta7600002 {
            get {
                return ResourceManager.GetString("AlertaDividendosCobradosCta7600002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuadre entre TOTAL RV y PLUSVALÍAS/MINUSVALÍAS: {0}.
        /// </summary>
        public static string AlertaPlusvMinusvTotalRV {
            get {
                return ResourceManager.GetString("AlertaPlusvMinusvTotalRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han encontrado ampliaciones de capital:.
        /// </summary>
        public static string AlertaRentaVarAmplCap {
            get {
                return ResourceManager.GetString("AlertaRentaVarAmplCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han encontrado cambios de ISIN:.
        /// </summary>
        public static string AlertaRentaVarCambiosIsins {
            get {
                return ResourceManager.GetString("AlertaRentaVarCambiosIsins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los siguientes códigos no se han tratado como operaciones corporativas:.
        /// </summary>
        public static string AlertaRentaVarOperCorpCods {
            get {
                return ResourceManager.GetString("AlertaRentaVarOperCorpCods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuadre CÍCLICO-DEFENSIVO: {0:N2}..
        /// </summary>
        public static string AlertaVarPatrADescuadreCicDef {
            get {
                return ResourceManager.GetString("AlertaVarPatrADescuadreCicDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuadre entre la suma de la columna TOTAL y la suma de la fila TOTAL RENDIMIENTOS: {0:N2}. .
        /// </summary>
        public static string AlertaVarPatrADescuadreColTotalFilaTotal {
            get {
                return ResourceManager.GetString("AlertaVarPatrADescuadreColTotalFilaTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuadre en Total Patrimonio Final: {0:N2}..
        /// </summary>
        public static string AlertaVarPatrADescuadrePatrimonioFinal {
            get {
                return ResourceManager.GetString("AlertaVarPatrADescuadrePatrimonioFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuadre elevado en variación de precios: {0:N2}..
        /// </summary>
        public static string AlertaVarPatrADescuadrePrecios {
            get {
                return ResourceManager.GetString("AlertaVarPatrADescuadrePrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuadre SMALL-LARGE: {0:N2}..
        /// </summary>
        public static string AlertaVarPatrADescuadreSmallMidLar {
            get {
                return ResourceManager.GetString("AlertaVarPatrADescuadreSmallMidLar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ha introducido la comisión fija pagada?.
        /// </summary>
        public static string AlertaVarPatrBFijaPagada {
            get {
                return ResourceManager.GetString("AlertaVarPatrBFijaPagada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Empresa.
        /// </summary>
        public static string AñadirInstrumentosEmpresas_Title {
            get {
                return ResourceManager.GetString("AñadirInstrumentosEmpresas_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string Año_Text {
            get {
                return ResourceManager.GetString("Año_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar_Button {
            get {
                return ResourceManager.GetString("Cancelar_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORE.
        /// </summary>
        public static string CcrCore {
            get {
                return ResourceManager.GetString("CcrCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondos Renta Variable.
        /// </summary>
        public static string CcrCoreFondos {
            get {
                return ResourceManager.GetString("CcrCoreFondos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renta Variable Euro.
        /// </summary>
        public static string CcrCoreRvaEur {
            get {
                return ResourceManager.GetString("CcrCoreRvaEur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renta Variable Otros.
        /// </summary>
        public static string CcrCoreRvaOtros {
            get {
                return ResourceManager.GetString("CcrCoreRvaOtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renta Variable Dólar.
        /// </summary>
        public static string CcrCoreRvaUsd {
            get {
                return ResourceManager.GetString("CcrCoreRvaUsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercado Monetario.
        /// </summary>
        public static string CcrLiqMmo {
            get {
                return ResourceManager.GetString("CcrLiqMmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesorería y otros (garantías, pendientes de liquidar).
        /// </summary>
        public static string CcrLiqTesoreriaOtros {
            get {
                return ResourceManager.GetString("CcrLiqTesoreriaOtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIQUIDEZ.
        /// </summary>
        public static string CcrLiquidez {
            get {
                return ResourceManager.GetString("CcrLiquidez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETORNO ABSOLUTO.
        /// </summary>
        public static string CcrRab {
            get {
                return ResourceManager.GetString("CcrRab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENTA FIJA.
        /// </summary>
        public static string CcrRfi {
            get {
                return ResourceManager.GetString("CcrRfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emisiones.
        /// </summary>
        public static string CcrRfiEmisiones {
            get {
                return ResourceManager.GetString("CcrRfiEmisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondos.
        /// </summary>
        public static string CcrRfiFondos {
            get {
                return ResourceManager.GetString("CcrRfiFondos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENTA FIJA MIXTA.
        /// </summary>
        public static string CcrRfm {
            get {
                return ResourceManager.GetString("CcrRfm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondos.
        /// </summary>
        public static string CcrRfmFondos {
            get {
                return ResourceManager.GetString("CcrRfmFondos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENTA VARIABLE MIXTA.
        /// </summary>
        public static string CcrRvm {
            get {
                return ResourceManager.GetString("CcrRvm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondos.
        /// </summary>
        public static string CcrRvmFondos {
            get {
                return ResourceManager.GetString("CcrRvmFondos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRADING.
        /// </summary>
        public static string CcrTrading {
            get {
                return ResourceManager.GetString("CcrTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondos Euro.
        /// </summary>
        public static string CcrTradingFondosEur {
            get {
                return ResourceManager.GetString("CcrTradingFondosEur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renta Variable Euro.
        /// </summary>
        public static string CcrTradingRvaEur {
            get {
                return ResourceManager.GetString("CcrTradingRvaEur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renta Variable Dólar.
        /// </summary>
        public static string CcrTradingRvaUsd {
            get {
                return ResourceManager.GetString("CcrTradingRvaUsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca CodigoICFondo..
        /// </summary>
        public static string CodigoICFondo_Message {
            get {
                return ResourceManager.GetString("CodigoICFondo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &apos;Código IC&apos; es obligatorio..
        /// </summary>
        public static string CodigoIcObligatorio_Mens {
            get {
                return ResourceManager.GetString("CodigoIcObligatorio_Mens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código introducido ya existe..
        /// </summary>
        public static string CodigoYaExiste_Message {
            get {
                return ResourceManager.GetString("CodigoYaExiste_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado la columna &quot;{0}&quot; o no se encuentra en la posición correcta..
        /// </summary>
        public static string ColumnaExcelErronea {
            get {
                return ResourceManager.GetString("ColumnaExcelErronea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está conectado a un entorno de pruebas..
        /// </summary>
        public static string ConexionDesarrollo {
            get {
                return ResourceManager.GetString("ConexionDesarrollo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Corrección necesaria: .
        /// </summary>
        public static string Correcion_SubMens {
            get {
                return ResourceManager.GetString("Correcion_SubMens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion_Label {
            get {
                return ResourceManager.GetString("Descripcion_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción introducida ya existe..
        /// </summary>
        public static string DescripcionExiste_Message {
            get {
                return ResourceManager.GetString("DescripcionExiste_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción larga.
        /// </summary>
        public static string DescripcionLarga_Label {
            get {
                return ResourceManager.GetString("DescripcionLarga_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta documento publicitario, así como los datos, opiniones, estimaciones, previsiones y recomendaciones contenidas en la misma, han sido elaborados por GVC Gaesco Gestión, S.G.I.I.C., S.A.U. (en adelante &quot;GVC Gaesco Gestión&quot;), con la finalidad de proporcionar información general a la fecha de emisión del informe respecto a la Institución de Inversión Colectiva identificada en el mismo, y están sujetos a cambio sin previo aviso por parte de la sociedad gestora. GVC Gaesco Gestión no asume compromiso alguno d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        public static string DividendosCobrados_VM_Ajustes {
            get {
                return ResourceManager.GetString("DividendosCobrados_VM_Ajustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El DNI introducido ya existe..
        /// </summary>
        public static string DNIExiste_Message {
            get {
                return ResourceManager.GetString("DNIExiste_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento no válido o sin datos..
        /// </summary>
        public static string DocumentoNoValido_Mens {
            get {
                return ResourceManager.GetString("DocumentoNoValido_Mens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro duplicado. No se ha podido insertar..
        /// </summary>
        public static string DuplicateKeyExceptionMessage {
            get {
                return ResourceManager.GetString("DuplicateKeyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Empresa.
        /// </summary>
        public static string EditarInstrumentosEmpresas_Title {
            get {
                return ResourceManager.GetString("EditarInstrumentosEmpresas_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro que desea eliminar?.
        /// </summary>
        public static string EliminarConfirmacion {
            get {
                return ResourceManager.GetString("EliminarConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error:.
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error de conexión con la base de datos..
        /// </summary>
        public static string ErrorConexion {
            get {
                return ResourceManager.GetString("ErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al generar sección: .
        /// </summary>
        public static string ErrorSeccion {
            get {
                return ResourceManager.GetString("ErrorSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar Informe.
        /// </summary>
        public static string GenerarInforme_Button {
            get {
                return ResourceManager.GetString("GenerarInforme_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Guardar_Button {
            get {
                return ResourceManager.GetString("Guardar_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GVC Gaesco.
        /// </summary>
        public static string HeaderGVC_MessageBox {
            get {
                return ResourceManager.GetString("HeaderGVC_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento no tiene ninguna Hoja con el nombre &quot;dades&quot;..
        /// </summary>
        public static string HojaDades {
            get {
                return ResourceManager.GetString("HojaDades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Bloomberg.
        /// </summary>
        public static string ImportarBloomberg_Title {
            get {
                return ResourceManager.GetString("ImportarBloomberg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la plantilla Excel que contenga los instrumentos a importar..
        /// </summary>
        public static string ImportarExcel_Text {
            get {
                return ResourceManager.GetString("ImportarExcel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Instrumentos.
        /// </summary>
        public static string ImportarInstrumentos_Title {
            get {
                return ResourceManager.GetString("ImportarInstrumentos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar equivalencias ISINS.
        /// </summary>
        public static string ImportarIsins_Title {
            get {
                return ResourceManager.GetString("ImportarIsins_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;CORE/TRADING&quot; no ha sido informado en la importación para los siguientes instrumentos: .
        /// </summary>
        public static string ImportCoreTrading {
            get {
                return ResourceManager.GetString("ImportCoreTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código Indice introducido ya existe..
        /// </summary>
        public static string IndiceExiste_Message {
            get {
                return ResourceManager.GetString("IndiceExiste_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca código..
        /// </summary>
        public static string IntroduceCodigo_Message {
            get {
                return ResourceManager.GetString("IntroduceCodigo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca Aportación.
        /// </summary>
        public static string IntroduzcaAportacion_Message {
            get {
                return ResourceManager.GetString("IntroduzcaAportacion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca BPA año informe máximo..
        /// </summary>
        public static string IntroduzcaBPAAñoMax {
            get {
                return ResourceManager.GetString("IntroduzcaBPAAñoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca BPA año informe mínimo..
        /// </summary>
        public static string IntroduzcaBPAAñoMin {
            get {
                return ResourceManager.GetString("IntroduzcaBPAAñoMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca código ISIN..
        /// </summary>
        public static string IntroduzcaCodigoIsin_Message {
            get {
                return ResourceManager.GetString("IntroduzcaCodigoIsin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca valor ComisionDepositaria..
        /// </summary>
        public static string IntroduzcaComisionDepositaria_Message {
            get {
                return ResourceManager.GetString("IntroduzcaComisionDepositaria_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca descripción..
        /// </summary>
        public static string IntroduzcaDescripcion_Message {
            get {
                return ResourceManager.GetString("IntroduzcaDescripcion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca deuda neta capitalización previsión máxima..
        /// </summary>
        public static string IntroduzcaDeudaNetaCapPrevMax {
            get {
                return ResourceManager.GetString("IntroduzcaDeudaNetaCapPrevMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca deuda neta capitalización previsión mínima..
        /// </summary>
        public static string IntroduzcaDeudaNetaCapPrevMin {
            get {
                return ResourceManager.GetString("IntroduzcaDeudaNetaCapPrevMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca deuda neta capitalización máxima..
        /// </summary>
        public static string IntroduzcaDeudaNetCapMax {
            get {
                return ResourceManager.GetString("IntroduzcaDeudaNetCapMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca deuda neta capitalización mínima..
        /// </summary>
        public static string IntroduzcaDeudaNetCapMin {
            get {
                return ResourceManager.GetString("IntroduzcaDeudaNetCapMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca DNI..
        /// </summary>
        public static string IntroduzcaDNI_Message {
            get {
                return ResourceManager.GetString("IntroduzcaDNI_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca descuento fundamental máximo..
        /// </summary>
        public static string IntroduzcaDtoFundamentalMax {
            get {
                return ResourceManager.GetString("IntroduzcaDtoFundamentalMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca descuento fundamental mínimo..
        /// </summary>
        public static string IntroduzcaDtoFundamentalMin {
            get {
                return ResourceManager.GetString("IntroduzcaDtoFundamentalMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca fecha..
        /// </summary>
        public static string IntroduzcaFecha_Message {
            get {
                return ResourceManager.GetString("IntroduzcaFecha_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca Fórmula.
        /// </summary>
        public static string IntroduzcaFormula_Message {
            get {
                return ResourceManager.GetString("IntroduzcaFormula_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca índice..
        /// </summary>
        public static string IntroduzcaIndice_Message {
            get {
                return ResourceManager.GetString("IntroduzcaIndice_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca PER año informe máximo..
        /// </summary>
        public static string IntroduzcaPERAñoMax {
            get {
                return ResourceManager.GetString("IntroduzcaPERAñoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca PER año informe mínimo..
        /// </summary>
        public static string IntroduzcaPERAñoMin {
            get {
                return ResourceManager.GetString("IntroduzcaPERAñoMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca PER previsión máximo..
        /// </summary>
        public static string IntroduzcaPERPrevisiónMax {
            get {
                return ResourceManager.GetString("IntroduzcaPERPrevisiónMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca PER previsión mínimo..
        /// </summary>
        public static string IntroduzcaPERPrevisiónMin {
            get {
                return ResourceManager.GetString("IntroduzcaPERPrevisiónMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca precio VC máximo..
        /// </summary>
        public static string IntroduzcaPrecioVCMax {
            get {
                return ResourceManager.GetString("IntroduzcaPrecioVCMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca precio VC mínimo..
        /// </summary>
        public static string IntroduzcaPrecioVCMin {
            get {
                return ResourceManager.GetString("IntroduzcaPrecioVCMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca previsión máxima..
        /// </summary>
        public static string IntroduzcaPrevisionMax {
            get {
                return ResourceManager.GetString("IntroduzcaPrevisionMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca previsión mínima..
        /// </summary>
        public static string IntroduzcaPrevisionMin {
            get {
                return ResourceManager.GetString("IntroduzcaPrevisionMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca rentabilidades año informe máximas..
        /// </summary>
        public static string IntroduzcaRentabilidadesAñoMax {
            get {
                return ResourceManager.GetString("IntroduzcaRentabilidadesAñoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca rentabilidades año informe mínimas..
        /// </summary>
        public static string IntroduzcaRentabilidadesAñoMin {
            get {
                return ResourceManager.GetString("IntroduzcaRentabilidadesAñoMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca rentabilidades previsión máximas..
        /// </summary>
        public static string IntroduzcaRentabilidadesPrevisionMax {
            get {
                return ResourceManager.GetString("IntroduzcaRentabilidadesPrevisionMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca rentabilidades previsión mínimas..
        /// </summary>
        public static string IntroduzcaRentabilidadesPrevisionMin {
            get {
                return ResourceManager.GetString("IntroduzcaRentabilidadesPrevisionMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca valor TasaGestionAnual..
        /// </summary>
        public static string IntroduzcaTasaGestionAnual_Message {
            get {
                return ResourceManager.GetString("IntroduzcaTasaGestionAnual_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca Titular.
        /// </summary>
        public static string IntroduzcaTitular_Message {
            get {
                return ResourceManager.GetString("IntroduzcaTitular_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca valor fundamental máximo..
        /// </summary>
        public static string IntroduzcaValorFundamentalMax {
            get {
                return ResourceManager.GetString("IntroduzcaValorFundamentalMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca valor fundamental mínimo..
        /// </summary>
        public static string IntroduzcaValorFundamentalMin {
            get {
                return ResourceManager.GetString("IntroduzcaValorFundamentalMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código ISIN introducido ya existe..
        /// </summary>
        public static string IsinExiste_Message {
            get {
                return ResourceManager.GetString("IsinExiste_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca IsinFondo.
        /// </summary>
        public static string IsinFondo_Message {
            get {
                return ResourceManager.GetString("IsinFondo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercado Monetario.
        /// </summary>
        public static string MMO {
            get {
                return ResourceManager.GetString("MMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercado Monetario / Liquidez.
        /// </summary>
        public static string MMOLiq {
            get {
                return ResourceManager.GetString("MMOLiq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOOMBERG: No se encuentran los siguientes ISINS en la plantilla de  Bloomberg importada..
        /// </summary>
        public static string NoBloomImp_Men {
            get {
                return ResourceManager.GetString("NoBloomImp_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTRUMENTOS: No se encuentran los siguientes ISINS en la plantilla de instrumentos importados..
        /// </summary>
        public static string NoInstrImp_Mens {
            get {
                return ResourceManager.GetString("NoInstrImp_Mens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edite esta sección dentro de la plantilla para rellenar todos los parámetros necesarios..
        /// </summary>
        public static string ParametrosSeccionIncompletos {
            get {
                return ResourceManager.GetString("ParametrosSeccionIncompletos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe añadir algún partícipe para generar la sección PartícipesSalat.
        /// </summary>
        public static string ParticipesIncompletos {
            get {
                return ResourceManager.GetString("ParticipesIncompletos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        public static string PlusvaliasDividendos_VM_Ajustes {
            get {
                return ResourceManager.GetString("PlusvaliasDividendos_VM_Ajustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe rellenar el parámetro &quot;% Estrategias RA&quot;.
        /// </summary>
        public static string PorcEstratRaIncompleto {
            get {
                return ResourceManager.GetString("PorcEstratRaIncompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca ReferenciaTAE.
        /// </summary>
        public static string ReferenciaTAE_Message {
            get {
                return ResourceManager.GetString("ReferenciaTAE_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTRIBUCIÓN PATRIMONIO.
        /// </summary>
        public static string Report_DistribucionPatrimonioNovarex {
            get {
                return ResourceManager.GetString("Report_DistribucionPatrimonioNovarex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIC: COMPRAS Y VENTAS REALIZADAS DURANTE EL EJERCICIO.
        /// </summary>
        public static string Report_IIC_VentasEjercicio {
            get {
                return ResourceManager.GetString("Report_IIC_VentasEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÍNDICE SEGÚN MERCADOS Y DIVISAS.
        /// </summary>
        public static string Report_IndicePreconfiguradoNovarex {
            get {
                return ResourceManager.GetString("Report_IndicePreconfiguradoNovarex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTADO RENTA FIJA.
        /// </summary>
        public static string Report_ListadoRentaFijaNovarex {
            get {
                return ResourceManager.GetString("Report_ListadoRentaFijaNovarex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string ReportFromText {
            get {
                return ResourceManager.GetString("ReportFromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        public static string ReportPageText {
            get {
                return ResourceManager.GetString("ReportPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revise las validaciones previas necesarias para poder generar el informe.
        /// </summary>
        public static string ReviseValidaciones_Mens {
            get {
                return ResourceManager.GetString("ReviseValidaciones_Mens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Deuda que teníamos en cartera a {0:dd/MM/yyyy} y no se han vendido en {1:yyyy}.
        /// </summary>
        public static string RfGrupo01 {
            get {
                return ResourceManager.GetString("RfGrupo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Deuda que teníamos en cartera el {0:dd/MM/yyyy} y se ha amortizado en {1:yyyy}.
        /// </summary>
        public static string RfGrupo02 {
            get {
                return ResourceManager.GetString("RfGrupo02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Deuda que teníamos en cartera el {0:dd/MM/yyyy} y se ha vendido en {1:yyyy}.
        /// </summary>
        public static string RfGrupo03 {
            get {
                return ResourceManager.GetString("RfGrupo03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) Deuda que se ha comprado en {0:yyyy} y no se ha vendido en {0:yyyy}.
        /// </summary>
        public static string RfGrupo04 {
            get {
                return ResourceManager.GetString("RfGrupo04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) Deuda comprada y vendida en {0:yyyy}.
        /// </summary>
        public static string RfGrupo05 {
            get {
                return ResourceManager.GetString("RfGrupo05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6) IICs.
        /// </summary>
        public static string RfGrupo06 {
            get {
                return ResourceManager.GetString("RfGrupo06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7) Derivados.
        /// </summary>
        public static string RfGrupo07 {
            get {
                return ResourceManager.GetString("RfGrupo07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPRA.
        /// </summary>
        public static string RVCabCompra {
            get {
                return ResourceManager.GetString("RVCabCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRECIO.
        /// </summary>
        public static string RVCabPrecio {
            get {
                return ResourceManager.GetString("RVCabPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Valores que teníamos en cartera a {0} y no se han vendido en {1}.
        /// </summary>
        public static string RVGrupo01 {
            get {
                return ResourceManager.GetString("RVGrupo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Valores que teníamos en cartera el {0} y se han vendido en {1}.
        /// </summary>
        public static string RVGrupo02 {
            get {
                return ResourceManager.GetString("RVGrupo02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Valores que se han comprado y vendido en {0}.
        /// </summary>
        public static string RVGrupo03 {
            get {
                return ResourceManager.GetString("RVGrupo03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) Valores que se han comprado en {0} y no se han vendido en {1}.
        /// </summary>
        public static string RVGrupo04 {
            get {
                return ResourceManager.GetString("RVGrupo04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) Derivados.
        /// </summary>
        public static string RVGrupo05 {
            get {
                return ResourceManager.GetString("RVGrupo05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6) IIC.
        /// </summary>
        public static string RVGrupo06 {
            get {
                return ResourceManager.GetString("RVGrupo06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7) PATRIMONIALISTA.
        /// </summary>
        public static string RVGrupo07 {
            get {
                return ResourceManager.GetString("RVGrupo07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8) CCCP.
        /// </summary>
        public static string RVGrupo08 {
            get {
                return ResourceManager.GetString("RVGrupo08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9) PERSISTENCIA.
        /// </summary>
        public static string RVGrupo09 {
            get {
                return ResourceManager.GetString("RVGrupo09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10) OTROS.
        /// </summary>
        public static string RVGrupo10 {
            get {
                return ResourceManager.GetString("RVGrupo10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11) Garantizados / Estructurados.
        /// </summary>
        public static string RVGrupo11 {
            get {
                return ResourceManager.GetString("RVGrupo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12) Divisas.
        /// </summary>
        public static string RVGrupo12 {
            get {
                return ResourceManager.GetString("RVGrupo12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13) Commodities.
        /// </summary>
        public static string RVGrupo13 {
            get {
                return ResourceManager.GetString("RVGrupo13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección: .
        /// </summary>
        public static string Seccion_SubMens {
            get {
                return ResourceManager.GetString("Seccion_SubMens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una plantilla..
        /// </summary>
        public static string SeleccionePlantilla_Message {
            get {
                return ResourceManager.GetString("SeleccionePlantilla_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIN RATING.
        /// </summary>
        public static string SinRating {
            get {
                return ResourceManager.GetString("SinRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENTA FIJA: COMPRAS EJERCICIO .
        /// </summary>
        public static string SubTituloComprasRF {
            get {
                return ResourceManager.GetString("SubTituloComprasRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVOLUCIÓN PATRIMONIO GESTIONADO.
        /// </summary>
        public static string SubtituloGestionadoRP_ValorLiquidativo {
            get {
                return ResourceManager.GetString("SubtituloGestionadoRP_ValorLiquidativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVOLUCIÓN VALOR LIQUIDATIVO.
        /// </summary>
        public static string SubtituloLiquidativoRP_ValorLiquidativo {
            get {
                return ResourceManager.GetString("SubtituloLiquidativoRP_ValorLiquidativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENTA FIJA: VENTAS Y AMORTIZACIONES EJERCICIO .
        /// </summary>
        public static string SubTituloVentasRF {
            get {
                return ResourceManager.GetString("SubTituloVentasRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELACIÓN REINTEGROS.
        /// </summary>
        public static string SuscripcionesReembolsosRep_Reintegros {
            get {
                return ResourceManager.GetString("SuscripcionesReembolsosRep_Reintegros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REINTEGRO.
        /// </summary>
        public static string SuscripcionesReembolsosVM_Reintegro {
            get {
                return ResourceManager.GetString("SuscripcionesReembolsosVM_Reintegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectivo {0} sin cupón corrido.
        /// </summary>
        public static string TextCabeceraEfectivoFinFechaSinCup {
            get {
                return ResourceManager.GetString("TextCabeceraEfectivoFinFechaSinCup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectivo venta sin cupón corrido.
        /// </summary>
        public static string TextCabeceraEfectivoFinVtaSinCup {
            get {
                return ResourceManager.GetString("TextCabeceraEfectivoFinVtaSinCup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectivo {0} sin cupón corrido.
        /// </summary>
        public static string TextCabeceraEfectivoIniFecha {
            get {
                return ResourceManager.GetString("TextCabeceraEfectivoIniFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectivo compra sin cupón corrido.
        /// </summary>
        public static string TextCabeceraEfectivoIniNoFecha {
            get {
                return ResourceManager.GetString("TextCabeceraEfectivoIniNoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Ampliaciones de capital/- Reducciones de capital / Autocartera.
        /// </summary>
        public static string TextoAmpliacionesCapitalReduccionesCapitalAutocartera {
            get {
                return ResourceManager.GetString("TextoAmpliacionesCapitalReduccionesCapitalAutocartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Suscripciones/- Reembolsos.
        /// </summary>
        public static string TextoSuscripcionesReembolsos {
            get {
                return ResourceManager.GetString("TextoSuscripcionesReembolsos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTRIBUCIÓN EXPOSICIÓN MERCADO (TIPO DE ACTIVO).
        /// </summary>
        public static string TituloGrafExposMercTipoAct {
            get {
                return ResourceManager.GetString("TituloGrafExposMercTipoAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTRIBUCIÓN EXPOSICIÓN MERCADO (TIPO DE PRODUCTO).
        /// </summary>
        public static string TituloGrafExposMercTipoProd {
            get {
                return ResourceManager.GetString("TituloGrafExposMercTipoProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTICIPACIONES.
        /// </summary>
        public static string TituloReport_Participes {
            get {
                return ResourceManager.GetString("TituloReport_Participes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENTABILIDAD DE LA CARTERA DESDE ORIGEN.
        /// </summary>
        public static string TituloReport_RentabilidadCarteraSolemeg {
            get {
                return ResourceManager.GetString("TituloReport_RentabilidadCarteraSolemeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF: COMPRAS Y VENTAS REALIZADAS DURANTE EL EJERCICIO .
        /// </summary>
        public static string TituloReport_RfComprasVentasEjercicio {
            get {
                return ResourceManager.GetString("TituloReport_RfComprasVentasEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENTA VARIABLE: COMPRAS REALIZADAS DURANTE EL EJERCICIO .
        /// </summary>
        public static string TituloReport_RvComprasRealizadasEjercicio {
            get {
                return ResourceManager.GetString("TituloReport_RvComprasRealizadasEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUSCRIPCIONES-REEMBOLSOS.
        /// </summary>
        public static string TituloReport_SubscripcionesReembolso {
            get {
                return ResourceManager.GetString("TituloReport_SubscripcionesReembolso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESGLOSE DE GASTOS.
        /// </summary>
        public static string TituloReport_VariacionPatrimonialTituloReport_DesgloseGastos {
            get {
                return ResourceManager.GetString("TituloReport_VariacionPatrimonialTituloReport_DesgloseGastos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAFICO (BENCHMARK).
        /// </summary>
        public static string TituloReportBenchMarkPRO_25 {
            get {
                return ResourceManager.GetString("TituloReportBenchMarkPRO_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANÁLISIS POSICIONAMIENTO CARTERA.
        /// </summary>
        public static string TituloReportBurbujas {
            get {
                return ResourceManager.GetString("TituloReportBurbujas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETALLE CARTERA.
        /// </summary>
        public static string TituloReportCarteraCcrVolgaGamar {
            get {
                return ResourceManager.GetString("TituloReportCarteraCcrVolgaGamar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARTERA DE RENTA FIJA.
        /// </summary>
        public static string TituloReportCarteraRF {
            get {
                return ResourceManager.GetString("TituloReportCarteraRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTRIBUCIÓN DE PATRIMONIO(TIPO ACTIVO).
        /// </summary>
        public static string TituloReportCompCarteraTipoActivo {
            get {
                return ResourceManager.GetString("TituloReportCompCarteraTipoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTRIBUCIÓN DE PATRIMONIO (TIPO PRODUCTO).
        /// </summary>
        public static string TituloReportCompCarteraTipodeProducto {
            get {
                return ResourceManager.GetString("TituloReportCompCarteraTipodeProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPOSICIÓN CARTERA RENTA FIJA.
        /// </summary>
        public static string TituloReportCompCartRF {
            get {
                return ResourceManager.GetString("TituloReportCompCartRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPOSICIÓN CARTERA RENTA VARIABLE.
        /// </summary>
        public static string TituloReportCompCartRV {
            get {
                return ResourceManager.GetString("TituloReportCompCartRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTRIBUCIÓN PATRIMONIO (TIPO ACTIVO).
        /// </summary>
        public static string TituloReportCompPatrimonioTipoActivo {
            get {
                return ResourceManager.GetString("TituloReportCompPatrimonioTipoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTRIBUCIÓN PATRIMONIO (TIPO PRODUCTO).
        /// </summary>
        public static string TituloReportCompPatrimonioTipodeProducto {
            get {
                return ResourceManager.GetString("TituloReportCompPatrimonioTipodeProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTADOS EN RENTA VARIABLE E IICS DESDE ADQUISICIÓN.
        /// </summary>
        public static string TituloReportCompraVentaRespectoPrecioAdquisicion {
            get {
                return ResourceManager.GetString("TituloReportCompraVentaRespectoPrecioAdquisicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUPONES NETOS COBRADOS DURANTE EJERCICIO.
        /// </summary>
        public static string TituloReportCuponesCobrados {
            get {
                return ResourceManager.GetString("TituloReportCuponesCobrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIVIDENDOS COBRADOS DURANTE EL EJERCICIO.
        /// </summary>
        public static string TituloReportDividendosCobradosPRO_10 {
            get {
                return ResourceManager.GetString("TituloReportDividendosCobradosPRO_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVOLUCIÓN ÍNDICES REFERENCIA.
        /// </summary>
        public static string TituloReportEvolucionIndicesBenchMarkPRO_03 {
            get {
                return ResourceManager.GetString("TituloReportEvolucionIndicesBenchMarkPRO_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVOLUCIÓN DE LOS MERCADOS.
        /// </summary>
        public static string TituloReportEvolucionMercados {
            get {
                return ResourceManager.GetString("TituloReportEvolucionMercados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVOLUCIÓN PATRIMONIO.
        /// </summary>
        public static string TituloReportEvolucionPatrimonioGuissona {
            get {
                return ResourceManager.GetString("TituloReportEvolucionPatrimonioGuissona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVOLUCIÓN PATRIMONIO-VALOR LIQUIDATIVO.
        /// </summary>
        public static string TituloReportEvolucionPatriOperacionesRealizadasGuissona {
            get {
                return ResourceManager.GetString("TituloReportEvolucionPatriOperacionesRealizadasGuissona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVOLUCIÓN RENTABILIDAD ANUAL.
        /// </summary>
        public static string TituloReportEvolucionRentabilidadGuissona {
            get {
                return ResourceManager.GetString("TituloReportEvolucionRentabilidadGuissona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTRIBUCIÓN DE PATRIMONIO POR DIVISAS.
        /// </summary>
        public static string TituloReportGraficoCompCarteraDivisas {
            get {
                return ResourceManager.GetString("TituloReportGraficoCompCarteraDivisas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTRIBUCIÓN EXPOSICIÓN MERCADO POR DIVISAS.
        /// </summary>
        public static string TituloReportGraficoCompPatrimonioDivisas {
            get {
                return ResourceManager.GetString("TituloReportGraficoCompPatrimonioDivisas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERACIONES R.V.
        /// </summary>
        public static string TituloReportOperacionesRentaVariable_II {
            get {
                return ResourceManager.GetString("TituloReportOperacionesRentaVariable_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVOLUCIÓN DE PATRIMONIO-VALOR LIQUIDATIVO.
        /// </summary>
        public static string TituloReportPatrimonio_ValorLiquidativoPRO_02 {
            get {
                return ResourceManager.GetString("TituloReportPatrimonio_ValorLiquidativoPRO_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENTA VARIABLE: PLUSVALÍAS Y DIVIDENDOS.
        /// </summary>
        public static string TituloReportPlusvaliasDividendos {
            get {
                return ResourceManager.GetString("TituloReportPlusvaliasDividendos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENTABILIDAD CARTERA.
        /// </summary>
        public static string TituloReportRentabilidadCarteraV1 {
            get {
                return ResourceManager.GetString("TituloReportRentabilidadCarteraV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENTA VARIABLE.
        /// </summary>
        public static string TituloReportRentabilidadVariable {
            get {
                return ResourceManager.GetString("TituloReportRentabilidadVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENTA FIJA.
        /// </summary>
        public static string TituloReportRentaFija {
            get {
                return ResourceManager.GetString("TituloReportRentaFija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARIACIÓN PATRIMONIAL.
        /// </summary>
        public static string TituloReportVariacionPatrimonialA {
            get {
                return ResourceManager.GetString("TituloReportVariacionPatrimonialA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SITUACIÓN PATRIMONIAL Y RENTABILIDAD.
        /// </summary>
        public static string TituloSituacionPatrimonialRentabilidad {
            get {
                return ResourceManager.GetString("TituloSituacionPatrimonialRentabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder ejecutar la aplicación debe instalar la última versión..
        /// </summary>
        public static string UltimaVersion_Message {
            get {
                return ResourceManager.GetString("UltimaVersion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-10 años.
        /// </summary>
        public static string Vto10Años {
            get {
                return ResourceManager.GetString("Vto10Años", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 1 año.
        /// </summary>
        public static string Vto1Año {
            get {
                return ResourceManager.GetString("Vto1Año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;1 mes.
        /// </summary>
        public static string Vto1Mes {
            get {
                return ResourceManager.GetString("Vto1Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-2 años.
        /// </summary>
        public static string Vto2Años {
            get {
                return ResourceManager.GetString("Vto2Años", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-3 años.
        /// </summary>
        public static string Vto3Años {
            get {
                return ResourceManager.GetString("Vto3Años", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-3 meses.
        /// </summary>
        public static string Vto3Meses {
            get {
                return ResourceManager.GetString("Vto3Meses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-5 años.
        /// </summary>
        public static string Vto5Años {
            get {
                return ResourceManager.GetString("Vto5Años", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-6 meses.
        /// </summary>
        public static string Vto6Meses {
            get {
                return ResourceManager.GetString("Vto6Meses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5- 7 años.
        /// </summary>
        public static string Vto7Años {
            get {
                return ResourceManager.GetString("Vto7Años", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIC’s R.F.
        /// </summary>
        public static string VtoIIC {
            get {
                return ResourceManager.GetString("VtoIIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 10 años.
        /// </summary>
        public static string VtoMas10Años {
            get {
                return ResourceManager.GetString("VtoMas10Años", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;5 años.
        /// </summary>
        public static string VtoSuperior {
            get {
                return ResourceManager.GetString("VtoSuperior", resourceCulture);
            }
        }
    }
}
