//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b3056
    {
        public string b3056_cod { get; set; }
        public string b3056_nomofi { get; set; }
        public string b3056_nomloc { get; set; }
        public int b3056_nivel { get; set; }
        public string b3056_hojnod { get; set; }
        public string b3056_nomred { get; set; }
        public string b3056_extval { get; set; }
        public string b3056_codblo { get; set; }
        public string b3001_tvdgte { get; set; }
        public string b3056_clains { get; set; }
        public string b3056_cnmv { get; set; }
        public int b3056_numdec { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b3056_datcre { get; set; }
        public string b3056_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b3056_datmod { get; set; }
        public string b3056_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public byte b3056_procom { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public string b3082_cod { get; set; }
        public string b3052_cod { get; set; }
        public bool b3056_compo { get; set; }
        public string b3094_cod { get; set; }
        public bool b3056_activo { get; set; }
    }
}
