//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b4051
    {
        public string b4051_nif { get; set; }
        public int b4051_cod { get; set; }
        public string b3001_cod { get; set; }
        public string b4051_nom { get; set; }
        public string b2054_cod { get; set; }
        public string b2054_codadm { get; set; }
        public System.DateTime b4051_datcon { get; set; }
        public System.DateTime b4051_datins { get; set; }
        public string b4051_nrcnmv { get; set; }
        public int b4051_pladur { get; set; }
        public string b4052_cod { get; set; }
        public decimal b4051_capini { get; set; }
        public decimal b4051_capmin { get; set; }
        public decimal b4051_capmax { get; set; }
        public decimal b4051_valnom { get; set; }
        public string b4051_aplliq { get; set; }
        public string b4051_audita { get; set; }
        public string b4051_resinf { get; set; }
        public byte b4051_fondte { get; set; }
        public byte b4051_garant { get; set; }
        public int b4051_plagar { get; set; }
        public decimal b4051_rentgar { get; set; }
        public string b4051_parimp { get; set; }
        public decimal b4051_invmip { get; set; }
        public string b4051_suspim { get; set; }
        public decimal b4051_susmip { get; set; }
        public byte b4051_pleinv { get; set; }
        public int b4051_dmaxre { get; set; }
        public int b4053_codcom { get; set; }
        public int b4053_codco2 { get; set; }
        public int b4051_impreo { get; set; }
        public int b4053_codsus { get; set; }
        public int b4053_codree { get; set; }
        public int b4053_coddtr { get; set; }
        public string b3062_cod { get; set; }
        public int b4053_codges { get; set; }
        public int b4053_coddep { get; set; }
        public int b4053_codsup { get; set; }
        public int b4053_codtas { get; set; }
        public int b4053_codcan { get; set; }
        public int b4053_codcus { get; set; }
        public string b2054_codnac { get; set; }
        public string b2054_codint { get; set; }
        public decimal b4051_tpcmar { get; set; }
        public string b5060_codbcn { get; set; }
        public string b5060_codgae { get; set; }
        public Nullable<System.DateTime> b4051_datbaj { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b4051_datcre { get; set; }
        public string b4051_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b4051_datmod { get; set; }
        public string b4051_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public string m1036_cod { get; set; }
        public string b4060_cod { get; set; }
        public int b4064_cod { get; set; }
        public int b3050_cod { get; set; }
        public decimal b4053_codadm { get; set; }
        public int b4053_codres { get; set; }
        public string b4051_admin { get; set; }
        public string b4051_tipres { get; set; }
        public byte b4051_crista { get; set; }
        public string b3078_cod { get; set; }
        public Nullable<int> b4053_codge3 { get; set; }
        public Nullable<int> b4053_codge2 { get; set; }
        public bool b4051_3dias { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public byte b4051_vendes { get; set; }
        public decimal b4051_volmax { get; set; }
        public byte b4051_opecre { get; set; }
        public decimal b4051_apalan { get; set; }
        public string b3078_codfit { get; set; }
        public int b4051_sumdia { get; set; }
        public int b4051_sumres { get; set; }
        public int b4051_dialiq { get; set; }
        public int b4051_preliq { get; set; }
        public int b4051_prepar { get; set; }
        public string b4051_logo { get; set; }
        public string b1001_codpro { get; set; }
        public decimal b4051_tpcirp { get; set; }
        public string b4051_nomcom { get; set; }
        public string b4051_esppla { get; set; }
        public string b4051_repart { get; set; }
        public int b4051_diasis { get; set; }
        public string b4051_esppl3 { get; set; }
        public string b4051_esppl2 { get; set; }
        public string b4030_tipcon { get; set; }
        public string a1001_codsus { get; set; }
        public string a1001_codree { get; set; }
        public string b4051_mod { get; set; }
        public Nullable<int> b4053_codler { get; set; }
        public Nullable<int> b4053_codleg { get; set; }
        public Nullable<int> b4053_codled { get; set; }
        public Nullable<int> b4053_codldr { get; set; }
        public string b4051_codext { get; set; }
        public string b4051_digcon { get; set; }
    
        public virtual b1001 b1001 { get; set; }
    }
}
