//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class b5004
    {
        public Nullable<int> b5004_num { get; set; }
        public string b5004_numord { get; set; }
        public string b5004_reford { get; set; }
        public string b5004_refanu { get; set; }
        public string m1036_cod { get; set; }
        public string b5004_motanu { get; set; }
        public int m1006_cod { get; set; }
        public string b2050_cod { get; set; }
        public string b2001_cod { get; set; }
        public string m1015_cod { get; set; }
        public string b3001_cod { get; set; }
        public string b3052_cod { get; set; }
        public System.DateTime b5004_datope { get; set; }
        public string b5004_horope { get; set; }
        public string m1008_codope { get; set; }
        public string b5004_refreg { get; set; }
        public Nullable<System.DateTime> b5004_datliq { get; set; }
        public Nullable<System.DateTime> b5004_datlqd { get; set; }
        public string m1036_codlqd { get; set; }
        public string b5001_clamov { get; set; }
        public string b5052_cod { get; set; }
        public string b5004_coment { get; set; }
        public decimal b5004_cantid { get; set; }
        public decimal b5004_valuni { get; set; }
        public decimal b5004_cambio { get; set; }
        public Nullable<System.DateTime> b5004_datanu { get; set; }
        public Nullable<System.DateTime> b5004_datses { get; set; }
        public string b3070_codcon { get; set; }
        public string b3070_codliq { get; set; }
        public string b5004_ctaliq { get; set; }
        public string b5004_ctadep { get; set; }
        public string b2054_coddep { get; set; }
        public string b3002_codmer { get; set; }
        public decimal b5004_impefe { get; set; }
        public string b5004_origen { get; set; }
        public string b2054_coddes { get; set; }
        public string b5004_sucdes { get; set; }
        public string b5004_ctades { get; set; }
        public string b5004_obs { get; set; }
        public byte b5004_provis { get; set; }
        public string b1010_nif { get; set; }
        public string b3056_clains { get; set; }
        public string b5013_mer { get; set; }
        public int b5004_numenv { get; set; }
        public string b5004_orienv { get; set; }
        public string b5004_insde1 { get; set; }
        public string b5004_insde2 { get; set; }
        public string b5004_insde3 { get; set; }
        public string b5004_insde4 { get; set; }
        public string b5004_insli1 { get; set; }
        public string b5004_insli2 { get; set; }
        public string b5004_insli3 { get; set; }
        public string b5004_insli4 { get; set; }
        public string b3072_loccod { get; set; }
        public decimal b5004_canliq { get; set; }
        public Nullable<int> b5001_numefe { get; set; }
        public byte b5004_salini { get; set; }
        public decimal b5004_cupcor { get; set; }
        public decimal b5004_tircom { get; set; }
        public string b5004_forpag { get; set; }
        public byte b5004_gaesco { get; set; }
        public decimal b5004_nomina { get; set; }
        public Nullable<int> b5018_num { get; set; }
        public byte b5004_comdiv { get; set; }
        public Nullable<int> m9915_num { get; set; }
        public string m1008_codcre { get; set; }
        public Nullable<System.DateTime> b5004_datcre { get; set; }
        public string b5004_horcre { get; set; }
        public string m1008_codmod { get; set; }
        public Nullable<System.DateTime> b5004_datmod { get; set; }
        public string b5004_hormod { get; set; }
        public Nullable<int> PROGRESS_RECID { get; set; }
        public int PROGRESS_RECID_IDENT_ { get; set; }
        public decimal b5004_impret { get; set; }
        public Nullable<System.DateTime> b5004_datant { get; set; }
        public Nullable<int> m9915_numenv { get; set; }
        public byte b5052_invdes { get; set; }
        public Nullable<int> b5004_numiic { get; set; }
        public byte b5052_modman { get; set; }
        public Nullable<System.DateTime> b5004_dinIIC { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public string b1001_codord { get; set; }
        public Nullable<int> b3040_num { get; set; }
        public Nullable<int> b8070_num { get; set; }
        public string b4030_tipcon { get; set; }
        public Nullable<decimal> b5004_factor { get; set; }
        public string b3001_codpar { get; set; }
        public Nullable<int> b5004_numanu { get; set; }
        public string b2054_codliq { get; set; }
        public decimal b5004_preexc { get; set; }
        public Nullable<int> m1006_codsin { get; set; }
        public string m1015_codsin { get; set; }
        public string b2050_codsin { get; set; }
        public string b2001_codsin { get; set; }
        public Nullable<int> b5704_num { get; set; }
        public Nullable<decimal> b5004_camcta { get; set; }
        public string b4062_cod { get; set; }
        public decimal b5004_faccan { get; set; }
        public decimal b5004_indfac { get; set; }
        public string b5114_ideasi { get; set; }
        public string b5004_ordasi { get; set; }
        public string b2054_codepa { get; set; }
        public string b8065_coddes { get; set; }
        public string b2054_codcom { get; set; }
        public string b5004_ccvdes { get; set; }
        public string b8062_cta { get; set; }
        public string b5004_pardes { get; set; }
        public string b8067_cta { get; set; }
        public string b5004_ord { get; set; }
        public string b8060_cod { get; set; }
        public string b8065_cod { get; set; }
        public Nullable<bool> b5004_sinecc { get; set; }
        public string b5004_orddes { get; set; }
        public string b2054_codmie { get; set; }
    
        public virtual b2001 b2001 { get; set; }
        public virtual b3001 b3001 { get; set; }
        public virtual b3002 b3002 { get; set; }
        public virtual b3040 b3040 { get; set; }
    }
}
