//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bloomberg
    {
        public string ISIN { get; set; }
        public int Año { get; set; }
        public int ColumnaEstimacion { get; set; }
        public Nullable<decimal> Capitalizacion { get; set; }
        public Nullable<decimal> Bpa0 { get; set; }
        public Nullable<decimal> BpaPrevision1 { get; set; }
        public Nullable<decimal> BpaPrevision2 { get; set; }
        public Nullable<decimal> BpaPrevision3 { get; set; }
        public Nullable<decimal> RentabilidadDividendo1 { get; set; }
        public Nullable<decimal> RentabilidadDividendo2 { get; set; }
        public Nullable<decimal> RentabilidadDividendo3 { get; set; }
        public Nullable<decimal> Per1 { get; set; }
        public Nullable<decimal> Per2 { get; set; }
        public Nullable<decimal> Per3 { get; set; }
        public Nullable<decimal> DeudaNetaCapitalizacion { get; set; }
        public Nullable<decimal> PrecioVc { get; set; }
        public Nullable<decimal> ValorFundamental { get; set; }
        public string GvcBloomberg { get; set; }
        public Nullable<decimal> DescuentoFundamental { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> MoodyDate { get; set; }
        public string MoodyRating { get; set; }
        public Nullable<System.DateTime> SPDate { get; set; }
        public string SPRating { get; set; }
        public Nullable<System.DateTime> FitchDate { get; set; }
        public string FitchRating { get; set; }
    }
}
