//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class gestioPf
    {
        public Nullable<System.Guid> ctxId { get; set; }
        public int numint { get; set; }
        public string b3001_cod { get; set; }
        public string b3052_cod { get; set; }
        public Nullable<decimal> b5005_cantid { get; set; }
        public string BuySell { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> OFecha { get; set; }
        public string OTipo { get; set; }
        public Nullable<int> ONum { get; set; }
        public Nullable<decimal> OPrecio { get; set; }
        public Nullable<decimal> OAPrecio { get; set; }
        public Nullable<decimal> OImporte { get; set; }
        public string ODivisa { get; set; }
        public Nullable<decimal> OCambio { get; set; }
        public Nullable<System.DateTime> CFecha { get; set; }
        public string CTipo { get; set; }
        public Nullable<int> CNum { get; set; }
        public Nullable<decimal> CPrecio { get; set; }
        public Nullable<decimal> CImporte { get; set; }
        public string CDivisa { get; set; }
        public Nullable<decimal> CCambio { get; set; }
        public Nullable<decimal> I3003Precio { get; set; }
        public Nullable<decimal> IPrecio { get; set; }
        public Nullable<decimal> ICambio { get; set; }
        public Nullable<decimal> Dividendos { get; set; }
        public Nullable<decimal> F3003Precio { get; set; }
        public Nullable<decimal> FPrecio { get; set; }
        public Nullable<decimal> FAPrecio { get; set; }
        public Nullable<decimal> FCambio { get; set; }
    }
}
