//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrumentos_Sectores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrumentos_Sectores()
        {
            this.Instrumentos_Importados = new HashSet<Instrumentos_Importados>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int IdCategoria { get; set; }
    
        public virtual Instrumentos_Categorias Instrumentos_Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instrumentos_Importados> Instrumentos_Importados { get; set; }
    }
}
