//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_RatiosCarteraRV
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public Nullable<decimal> BpaAñoInformeMinimo { get; set; }
        public Nullable<decimal> BpaAñoInformeMaximo { get; set; }
        public Nullable<decimal> BpaPrevisionMinimo { get; set; }
        public Nullable<decimal> BpaPrevisionMaximo { get; set; }
        public Nullable<decimal> RentabilidadesAñoInformeMinimo { get; set; }
        public Nullable<decimal> RentabilidadesAñoInformeMaximo { get; set; }
        public Nullable<decimal> RentabilidadesPrevisionMinimo { get; set; }
        public Nullable<decimal> RentabilidadesPrevisionMaximo { get; set; }
        public Nullable<decimal> PerAñoInformeMinimo { get; set; }
        public Nullable<decimal> PerAñoInformeMaximo { get; set; }
        public Nullable<decimal> PerPrevisionMinimo { get; set; }
        public Nullable<decimal> PerPrevisionMaximo { get; set; }
        public Nullable<decimal> DeudaNetaCapitalizacionMinimo { get; set; }
        public Nullable<decimal> DeudaNetaCapitalizacionMaximo { get; set; }
        public Nullable<decimal> PrecioVcMinimo { get; set; }
        public Nullable<decimal> PrecioVcMaximo { get; set; }
        public Nullable<decimal> ValorFundamentalMinimo { get; set; }
        public Nullable<decimal> ValorFundamentalMaximo { get; set; }
        public Nullable<decimal> DescuentoFundamentalMinimo { get; set; }
        public Nullable<decimal> DescuentoFundamentalMaximo { get; set; }
        public Nullable<decimal> PorcentajeCarteraMinMostrar { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
