//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_Diversificacion_Instrumentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parametros_Diversificacion_Instrumentos()
        {
            this.Parametros_Diversificacion_Instrumentos_Divisas = new HashSet<Parametros_Diversificacion_Instrumentos_Divisas>();
        }
    
        public int Id { get; set; }
        public int IdParametroDiversificacion { get; set; }
        public string IdInstrumento { get; set; }
    
        public virtual Instrumento Instrumento { get; set; }
        public virtual Parametros_Diversificacion Parametros_Diversificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametros_Diversificacion_Instrumentos_Divisas> Parametros_Diversificacion_Instrumentos_Divisas { get; set; }
    }
}
