//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantillas_Estrategias
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string IdTipoInstrumento { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Instrumentos_Tipos Instrumentos_Tipos { get; set; }
        public virtual Plantilla Plantilla { get; set; }
    }
}
