//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentaVariable_PrecioAjustado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentaVariable_PrecioAjustado()
        {
            this.RentaVariable_PrecioAjustado_NumO = new HashSet<RentaVariable_PrecioAjustado_NumO>();
        }
    
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string Isin { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public decimal NumeroTitulos { get; set; }
        public Nullable<decimal> PrecioIni { get; set; }
        public Nullable<decimal> PrecioFin { get; set; }
        public Nullable<decimal> PrecioFinEuros { get; set; }
        public Nullable<decimal> PrecioAjustado { get; set; }
        public Nullable<decimal> TipoCambioIni { get; set; }
        public Nullable<decimal> TipoCambioFin { get; set; }
        public long NumO { get; set; }
        public string TipoO { get; set; }
        public Nullable<long> NumC { get; set; }
        public string TipoC { get; set; }
        public Nullable<int> GrupoNuevo { get; set; }
        public string Grupo { get; set; }
        public string Estado { get; set; }
        public int Ejercicio { get; set; }
        public System.DateTime FechaInforme { get; set; }
        public bool IsVisible { get; set; }
        public bool Added { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentaVariable_PrecioAjustado_NumO> RentaVariable_PrecioAjustado_NumO { get; set; }
    }
}
