//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_RatiosCarteraRV
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string Sector { get; set; }
        public string DescripcionInstrumento { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> CapitalizacionBursatilEuros { get; set; }
        public decimal PorcentajeCartera { get; set; }
        public decimal PorcentajeSector { get; set; }
        public Nullable<decimal> ValorAñoInforme { get; set; }
        public Nullable<decimal> ValorAdquisicion { get; set; }
        public Nullable<decimal> BpaAño { get; set; }
        public Nullable<decimal> BpaPrevision { get; set; }
        public Nullable<decimal> RentabilidadDividendoAño { get; set; }
        public Nullable<decimal> RentabilidadDividendoPrevision { get; set; }
        public Nullable<decimal> PerAño { get; set; }
        public Nullable<decimal> PerPrevision { get; set; }
        public Nullable<decimal> DeudaNeta { get; set; }
        public Nullable<decimal> PrecioVc { get; set; }
        public Nullable<decimal> ValorFundamental { get; set; }
        public string GvcBloomberg { get; set; }
        public Nullable<decimal> DescuentoFundamental { get; set; }
        public decimal NumeroTitulos { get; set; }
        public Nullable<System.DateTime> FechaCotizacion { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
