//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports_IICs.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_GraficoCompPatrimonioTipoProducto
    {
        public int Id { get; set; }
        public string CodigoIC { get; set; }
        public string IsinPlantilla { get; set; }
        public string IdInstrumento { get; set; }
        public string DescInstrumento { get; set; }
        public string IdTipoInstrumento { get; set; }
        public string DescTipoInstrumento { get; set; }
        public decimal Patrimonio { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual Instrumento Instrumento { get; set; }
        public virtual Instrumentos_Tipos Instrumentos_Tipos { get; set; }
        public virtual Plantilla Plantilla { get; set; }
    }
}
